// Auto-generated by Furin. Do not edit manually.
/// <reference types="@teyik0/furin/env" />
import "@teyik0/furin/routes";

declare module "@teyik0/furin/routes" {
  interface RouteMap {
    "/": typeof import("./src/pages/index").route;
    "/rsc": typeof import("./src/pages/rsc").route;
    [
      path: `/board/${string}/card/${string}`
    ]: typeof import("./src/pages/board/[boardId]/card/[cardId]").route;
    [path: `/board/${string}`]: typeof import("./src/pages/board/[boardId]/index").route;
  }

  interface RoutePatternMap {
    "/": typeof import("./src/pages/index").route;
    "/board/:boardId": typeof import("./src/pages/board/[boardId]/index").route;
    "/board/:boardId/card/:cardId": typeof import("./src/pages/board/[boardId]/card/[cardId]").route;
    "/rsc": typeof import("./src/pages/rsc").route;
  }
}

declare module "@teyik0/furin" {
  interface FurinCacheTags {
    boards: "boards";
    cards: "cards";
  }
}
