// Auto-generated by Furin. Do not edit manually.
/// <reference types="@teyik0/furin/env" />
import "@teyik0/furin/link";

declare module "@teyik0/furin/link" {
  interface RouteManifest {
    "/": { search?: never };
    [key: `/board/${string}/card/${string}`]: { search?: never };
    [key: `/board/${string}`]: { search?: never };
  }
}
