// Auto-generated by Furin. Do not edit manually.
/// <reference types="@teyik0/furin/env" />
import "@teyik0/furin/link";

declare module "@teyik0/furin/link" {
  interface RouteManifest {
    "/": { search?: never };
    "/docs": { search?: never };
    "/docs/api-routes": { search?: never };
    "/docs/data-loading": { search?: never };
    "/docs/deployment": { search?: never };
    "/docs/dev-hmr": { search?: never };
    "/docs/getting-started": { search?: never };
    "/docs/layouts": { search?: never };
    "/docs/plugins": { search?: never };
    "/docs/rendering": { search?: never };
    "/docs/routing": { search?: never };
  }
}
