import { log } from "evlog";
import type React from "react";
import {
  createContext,
  createElement,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import type { RuntimeRoute } from "./client";
import type { ErrorComponent } from "./error";
import type { NotFoundComponent } from "./not-found";
import { FurinErrorBoundary, FurinNotFoundBoundary } from "./render/boundaries.tsx";
import { DefaultNotFoundScreen } from "./render/default-screens.tsx";

// ── Types ─────────────────────────────────────────────────────────────────────

/**
 * Augment this interface via declaration merging in furin-env.d.ts
 * to get type-safe `to` autocompletion and per-route `search` types on <Link>.
 *
 * @example
 * // furin-env.d.ts (auto-generated by Furin at project root)
 * import "@teyik0/furin/link";
 * declare module "@teyik0/furin/link" {
 *   interface RouteManifest {
 *     "/blog": { search?: { page?: number; tag?: string } };
 *     "/":     { search?: never };
 *     [key: `/blog/${string}`]: { search?: never };
 *   }
 * }
 */
// biome-ignore lint/suspicious/noEmptyInterface: intentionally augmentable via furin-env.d.ts
export interface RouteManifest {}

/**
 * The valid `to` pathname union derived from the augmented RouteManifest.
 * Falls back to `string` when furin-env.d.ts has not been generated yet.
 * When augmented, also includes `https://` and `http://` for external links.
 */
export type RouteTo = keyof RouteManifest extends never
  ? string
  : keyof RouteManifest | `https://${string}` | `http://${string}`;

/**
 * The typed search params for a given `to` pathname.
 * Falls back to a permissive record when RouteManifest is not augmented.
 */
export type RouteSearch<To extends RouteTo> = keyof RouteManifest extends never
  ? Record<string, string | number | boolean | null | undefined>
  : To extends keyof RouteManifest
    ? RouteManifest[To] extends { search?: infer S }
      ? S
      : undefined
    : undefined;

export type PreloadStrategy = false | "intent" | "viewport" | "render";

export interface LinkProps<To extends RouteTo = RouteTo>
  extends Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, "href" | "children"> {
  /**
   * Extra props merged onto the anchor when the link is active.
   * `isActive` is also passed so one function can handle both states.
   * Styles and classNames from `activeProps` win over the static props.
   */
  activeProps?: (opts: { isActive: boolean }) => React.AnchorHTMLAttributes<HTMLAnchorElement>;
  /** Static children or a render function receiving active state. */
  children?: React.ReactNode | ((state: { isActive: boolean }) => React.ReactNode);
  /** Prevents navigation and prefetch; adds aria-disabled="true". The href stays intact for right-click. */
  disabled?: boolean;
  /** Optional URL fragment (without the #). */
  hash?: string;
  /**
   * Extra props merged onto the anchor when the link is NOT active.
   * Styles and classNames from `inactiveProps` win over the static props.
   */
  inactiveProps?: () => React.AnchorHTMLAttributes<HTMLAnchorElement>;
  /** Preload strategy. Default: "intent" (preload on hover/focus). */
  preload?: PreloadStrategy;
  /** Delay in ms before intent preload triggers. Default: 50. */
  preloadDelay?: number;
  /** How long a preloaded entry stays fresh (ms). Default: 30_000. */
  preloadStaleTime?: number;
  /** If true, uses history.replaceState instead of pushState (no new history entry). */
  replace?: boolean;
  /**
   * Whether to scroll after SPA navigation. Default: true.
   * - If the destination href has a `#hash`, scrolls to that element.
   * - Otherwise scrolls to the top of the page.
   * Set to `false` to suppress all scroll behaviour (e.g. tab/drawer navigation).
   */
  resetScroll?: boolean;
  /** Typed search params for this route. Auto-completed from the route's query schema. */
  search?: RouteSearch<To>;
  to: To;
}

/**
 * Builds a full href string from a pathname, optional search params, and optional hash.
 * Null/undefined search values are omitted.
 *
 * @internal Exported for unit testing only.
 */
export function buildHref(
  to: string,
  search?: Record<string, unknown> | null,
  hash?: string
): string {
  let url = to;
  if (search && Object.keys(search).length > 0) {
    const params = new URLSearchParams();
    for (const [k, v] of Object.entries(search)) {
      if (v != null) {
        params.set(k, String(v));
      }
    }
    const qs = params.toString();
    if (qs) {
      url += `?${qs}`;
    }
  }
  if (hash) {
    url += `#${hash}`;
  }
  return url;
}

// ── Revalidation helpers ────────────────────────────────────────────────────────

/**
 * Parses the `X-Furin-Revalidate` response header and calls `invalidate` for
 * each path entry. Header format: `"/path1,/path2:layout,/path3"`
 *
 * Intended to be called from a `window.fetch` interceptor or SPA navigation
 * handler so that client-side prefetch caches are busted automatically whenever
 * a server-side `revalidatePath()` call is made within the same request.
 *
 * @example
 * ```ts
 * const res = await fetch("/api/publish");
 * applyRevalidateHeader(res.headers, (path, type) => {
 *   console.log("invalidate", path, type);
 * });
 * ```
 */
export function applyRevalidateHeader(
  headers: Headers,
  invalidate: (path: string, type?: "page" | "layout") => void
): void {
  const headerValue = headers.get("x-furin-revalidate");
  if (!headerValue) {
    return;
  }
  for (const entry of headerValue.split(",")) {
    const trimmed = entry.trim();
    if (!trimmed) {
      continue;
    }
    if (trimmed.endsWith(":layout")) {
      invalidate(trimmed.slice(0, -":layout".length), "layout");
    } else {
      invalidate(trimmed, "page");
    }
  }
}

// ── Auto-refresh helpers ───────────────────────────────────────────────────────

/**
 * Returns `true` when `currentPath` is targeted by at least one invalidation entry,
 * using the same matching rules as `invalidatePrefetch`:
 * - `type: 'page'` — exact pathname match (query string stripped)
 * - `type: 'layout'` — prefix match: the path itself OR any descendant
 *
 * @internal Exported for unit testing only.
 */
export function shouldAutoRefreshPath(
  currentPath: string,
  invalidations: ReadonlyArray<{ path: string; type: "page" | "layout" }>
): boolean {
  // Strip query string for comparison — revalidatePath works on pathnames
  const normalizedCurrent = currentPath.split("?")[0] ?? currentPath;
  return invalidations.some(({ path, type }) => {
    if (type === "page") {
      return path === normalizedCurrent;
    }
    // layout: match the path itself and all descendants
    const prefix = path === "/" || path.endsWith("/") ? path : `${path}/`;
    return normalizedCurrent === path || normalizedCurrent.startsWith(prefix);
  });
}

// ── Router context ─────────────────────────────────────────────────────────────

export interface RouterContextValue {
  /**
   * Sub-path prefix for static deployments (e.g. "/furin").
   * Empty string when the site is served from root.
   * Used by `Link` to build correct physical hrefs for the `<a>` element.
   */
  basePath: string;
  /** Current **logical** pathname + search (basePath stripped). Used by Link for active-state detection. */
  currentHref: string;
  defaultPreload: PreloadStrategy;
  defaultPreloadDelay: number;
  defaultPreloadStaleTime: number;
  /**
   * Evicts one or more prefetch cache entries, mirroring a `revalidatePath()` call
   * made on the server. Called automatically by the `window.fetch` interceptor when
   * the server emits `X-Furin-Revalidate` headers.
   *
   * - `type: 'page'` (default) — exact URL match
   * - `type: 'layout'` — prefix match (path + all nested children)
   */
  invalidatePrefetch: (path: string, type?: "page" | "layout") => void;
  isNavigating: boolean;
  navigate: (href: string, opts?: { replace?: boolean; resetScroll?: boolean }) => Promise<void>;
  prefetch: (href: string, opts?: { staleTime?: number }) => void;
  /**
   * Re-fetches the current page in-place: busts the prefetch cache entry, re-runs
   * loaders, and updates the rendered tree — without adding a history entry or
   * resetting scroll (unless `resetScroll: true` is passed).
   *
   * Prefer this over `navigate(window.location.pathname)` after a mutation.
   *
   * @example
   * ```tsx
   * const { refresh } = useRouter();
   * await apiClient.api.boards.post({ name });
   * await refresh();
   * ```
   */
  refresh: (opts?: { resetScroll?: boolean }) => Promise<void>;
}

export const RouterContext = createContext<RouterContextValue | null>(null);

/**
 * Returns the current router context.
 * Provides a graceful fallback (full-page navigation) when used outside RouterProvider.
 */
export function useRouter(): RouterContextValue {
  return (
    useContext(RouterContext) ?? {
      basePath: "",
      // Use the same "/" as SSR_FALLBACK_ROUTER so SSR and client render the
      // same active-state when no RouterProvider is present, avoiding hydration mismatches.
      currentHref: "/",
      navigate: (href) => {
        window.location.href = href;
        return Promise.resolve();
      },
      prefetch: () => {
        /* noop fallback */
      },
      invalidatePrefetch: () => {
        /* noop fallback */
      },
      refresh: () => {
        window.location.reload();
        return Promise.resolve();
      },
      isNavigating: false,
      defaultPreload: "intent",
      defaultPreloadDelay: 50,
      defaultPreloadStaleTime: 30_000,
    }
  );
}

// ── RouterProvider ─────────────────────────────────────────────────────────────

/**
 * Client-side mirror of `SegmentBoundary` from router.ts. Unlike the server
 * version this does NOT carry the directory path — it's purely a (depth,
 * fallback) pair because the client never reads files, only renders.
 *
 * Emitted by `generateHydrateEntry` from the scanned `segmentBoundaries`
 * array: each route's entry lists ONLY the directories on its path that
 * declare a convention file, so routes with no error.tsx / not-found.tsx
 * anywhere carry an empty list (or omit the field entirely).
 */
export interface ClientSegmentBoundary {
  depth: number;
  error?: ErrorComponent;
  notFound?: NotFoundComponent;
}

export interface ClientRoute {
  component?: React.ComponentType<Record<string, unknown>>;
  load: () => Promise<{
    default: { component: React.ComponentType<Record<string, unknown>>; _route: RuntimeRoute };
  }>;
  pageRoute?: RuntimeRoute;
  pattern: string;
  regex: RegExp;
  /**
   * Per-segment boundary chain, ordered shallow→deep. Each `depth` maps 1:1
   * to the route-chain index used on the server side, so `buildPageElement`
   * can interleave boundaries at the exact same positions that the server
   * used in `buildElement` — guaranteeing hydration consistency.
   */
  segmentBoundaries?: ClientSegmentBoundary[];
}

/**
 * A ClientRoute that has been loaded — component and pageRoute are guaranteed defined.
 * The initial route is eagerly loaded in the hydrate entry; subsequent routes are loaded
 * on navigation via fetchPageState.
 */
export type LoadedClientRoute = ClientRoute & {
  component: React.ComponentType<Record<string, unknown>>;
  pageRoute: RuntimeRoute;
};

export interface RouterProviderProps {
  /**
   * When `true` (default), the router automatically re-fetches the current page
   * whenever a server `revalidatePath()` call targets it. The signal is the
   * `X-Furin-Revalidate` header detected on any `window.fetch` response.
   *
   * Set to `false` to opt out and call `router.refresh()` manually instead.
   */
  autoRefresh?: boolean;
  /**
   * Sub-path prefix for static deployments (e.g. "/furin").
   * Must start with "/" and have no trailing slash.
   * Default: "" (site served from root).
   *
   * When set:
   * - `currentHref` stores **logical** paths (prefix stripped) for correct active-state detection.
   * - `navigate(logicalHref)` pushes `basePath + logicalHref` to browser history.
   * - `fetch` calls use the physical path `basePath + logicalHref`.
   */
  basePath?: string;
  defaultPreload?: PreloadStrategy;
  defaultPreloadDelay?: number;
  defaultPreloadStaleTime?: number;
  initialData: Record<string, unknown>;
  /**
   * Slice 10 — server-logged error digest threaded from
   * `__FURIN_DATA__.__furinError.digest`. Forwarded onto the root-level
   * `FurinErrorBoundary` so that if a client-side error escapes the
   * per-segment boundaries (root layout crash, hydration mismatch, …), the
   * fallback UI surfaces the id a user would find in server logs.
   * Undefined when the initial SSR response was successful (no server-side
   * error digest to correlate).
   */
  initialDigest: string | undefined;
  /**
   * The route matched at hydration time. `null` is a valid value ONLY when
   * `initialNotFound` is also provided — it signals the initial URL didn't
   * match any registered route (direct load to an unknown URL). The provider
   * then mounts in a "not-found" state so the root `not-found.tsx` hydrates
   * inside a live RouterContext — critical for Links in the not-found UI to
   * participate in SPA navigation instead of triggering a full-page reload.
   */
  initialMatch: LoadedClientRoute | null;
  /**
   * When set, the provider boots into the inline not-found state as if a
   * prior SPA navigation hit a 404. Callers set this when the server-rendered
   * HTML carries `__FURIN_DATA__.__furinStatus === 404` — either because the
   * loader threw `notFound()` (rare at hydration time) or, more commonly,
   * because the URL didn't match any client route and `initialMatch` is
   * `null`. In the unmatched-URL case the depth-0 `rootBoundaries` are used
   * as the boundary chain, matching the server's `renderRootNotFound` choice.
   */
  initialNotFound: { data?: unknown; message?: string } | undefined;
  /** Maximum number of prefetch cache entries. Oldest entry is evicted when exceeded. Default: 50. */
  prefetchCacheSize?: number;
  root: RuntimeRoute | null;
  routes: ClientRoute[];
}

interface RouterState {
  data: Record<string, unknown>;
  /** The canonical href after server-side redirects (e.g. query-default redirect). */
  finalHref?: string;
  /**
   * The currently rendered route.
   *
   * `null` is a valid value ONLY when `notFound` is also set — it signals the
   * initial URL didn't match any registered route (direct load to an unknown
   * URL). In that case the provider renders the root `not-found.tsx` directly
   * and waits for the next `navigate()` call to populate `match`. Every other
   * state (including loader-triggered `notFound()` on a matched route) keeps a
   * non-null `match`. Render code MUST guard on `notFound` before dereferencing.
   */
  match: LoadedClientRoute | null;
  /**
   * Slice 8 — set when the matched route's loader threw `notFound()` on the
   * server (signalled via `__FURIN_DATA__.__furinStatus === 404`). Triggers
   * inline rendering of the deepest segment-level not-found.tsx instead of
   * the normal layout+page tree, mirroring the server's `buildNotFoundElement`.
   */
  notFound?: { data?: unknown; message?: string };
  /**
   * Explicit boundary chain to use for the not-found render.
   *
   * - **Set** (typically to depth-0 only) when no client-side route matched the
   *   navigation URL — the root `not-found.tsx` is the correct fallback and no
   *   page-specific segment context exists.
   * - **Absent** when a matched route's loader called `notFound()`, in which
   *   case `match.segmentBoundaries` is used (preserves per-route not-found).
   */
  notFoundBoundaries?: ClientSegmentBoundary[] | undefined;
  title?: string;
}

/** @internal */
export interface CacheEntry {
  createdAt: number;
  promise: Promise<RouterState | null>;
  staleTime: number;
}

/** @internal Exported for unit testing only. */
export function shouldRefetch(entry: CacheEntry): boolean {
  return Date.now() - entry.createdAt > entry.staleTime;
}

const HASH_FRAGMENT_RE = /#.*$/;

function stripHashFromHref(href: string): string {
  return href.replace(HASH_FRAGMENT_RE, "");
}

// ── Slice 8 helpers — SPA 404 inline rendering ─────────────────────────────────

/**
 * Classification of a fetch response during SPA navigation. Returned by the
 * pure `classifySpaResponse` so `fetchPageState` stays a thin orchestrator.
 *
 * - `ok` — 2xx response with usable loader data; render normally.
 * - `not-found` — server signalled `__FURIN_DATA__.__furinStatus === 404`; the
 *   caller should render the not-found UI inline (no full-page reload).
 * - `bail` — any other non-2xx (5xx, stale-deploy, unparseable payload…);
 *   the caller falls back to a full-page navigation so the browser picks up
 *   whatever the server wants to send (could be an error page, redirect, etc.).
 *
 * @internal Exported for unit testing only.
 */
export type SpaResponseKind =
  | { kind: "ok" }
  | { kind: "not-found"; error: { data?: unknown; message?: string } }
  | { kind: "bail" };

/**
 * Pure classifier for an SPA-nav fetch result. Takes the HTTP status and the
 * already-parsed `__FURIN_DATA__` payload. The 404 signal is trusted over the
 * HTTP status (guards against proxies that rewrite status but preserve body),
 * while any other non-ok HTTP status triggers a bail even if the payload is
 * well-formed.
 *
 * @internal Exported for unit testing only.
 */
export function classifySpaResponse(
  status: number,
  data: Record<string, unknown> | null
): SpaResponseKind {
  if (!data) {
    return { kind: "bail" };
  }
  if (data.__furinStatus === 404) {
    const notFound = data.__furinNotFound as { data?: unknown; message?: string } | undefined;
    return { kind: "not-found", error: notFound ?? {} };
  }
  if (status >= 200 && status < 300) {
    return { kind: "ok" };
  }
  return { kind: "bail" };
}

/**
 * Picks the deepest not-found component declared on the match's boundary
 * chain. Mirrors the server's `route.notFound ?? root.notFound` selection:
 * since `segmentBoundaries` is ordered shallow→deep, the last entry with a
 * `notFound` wins. Returns undefined when no boundary on the chain declares
 * a not-found convention.
 *
 * @internal Exported for unit testing only.
 */
export function pickDeepestNotFound(
  boundaries: ClientSegmentBoundary[] | undefined
): NotFoundComponent | undefined {
  if (!boundaries) {
    return;
  }
  for (let i = boundaries.length - 1; i >= 0; i--) {
    const seg = boundaries[i];
    if (seg?.notFound) {
      return seg.notFound;
    }
  }
  return;
}

const DefaultClientNotFoundFallback: NotFoundComponent = ({ error }) =>
  createElement(DefaultNotFoundScreen, { message: error.message });

/**
 * Builds the bare not-found element rendered inline by RouterProvider on SPA
 * navigation when the server signalled a 404. Matches the server's
 * `buildNotFoundElement` exactly — NO layouts, NO segment boundaries, just the
 * deepest user-declared `not-found.tsx` (or the built-in default). Preserving
 * layouts on 404 is a deliberate non-goal for this slice: it would diverge
 * from the server's current behaviour and require coordinated changes on both
 * sides.
 *
 * Accepts the boundary chain directly (rather than a full `LoadedClientRoute`)
 * so callers can pass a subset (e.g. depth-0 only for unmatched URLs) without
 * fabricating a synthetic route object.
 *
 * @internal Exported for unit testing only.
 */
export function buildNotFoundPageElement(
  boundaries: ClientSegmentBoundary[] | undefined,
  error: { data?: unknown; message?: string }
): React.ReactNode {
  const Fallback = pickDeepestNotFound(boundaries) ?? DefaultClientNotFoundFallback;
  return createElement(Fallback, { error });
}

/**
 * Root-level safety-net options forwarded onto the outermost
 * `FurinErrorBoundary` that wraps the entire RouterProvider tree. See
 * `buildRouterTree` for the full rationale.
 */
export interface RootBoundaryOptions {
  /**
   * Server-logged error id propagated from `__FURIN_DATA__.__furinError.digest`.
   * When the server's SSR response carried a digest (loader error or shell
   * recovery) this value lets the client's fallback UI display the SAME id a
   * user would find in the server logs — without having to recompute and
   * potentially produce a different hash from a different error instance.
   */
  digest?: string;
  onReset?: () => void;
  resetKey?: string | number;
}

/**
 * Composes the outermost tree produced by `RouterProvider`:
 *
 *   <FurinErrorBoundary digest onReset resetKey>
 *     <RouterContext.Provider value={context}>
 *       {pageElement}
 *     </RouterContext.Provider>
 *   </FurinErrorBoundary>
 *
 * This top boundary is the LAST line of defence. Per-segment
 * `FurinErrorBoundary`s inserted by `buildPageElement` only wrap the page
 * subtree BELOW the root layout, so they cannot catch errors thrown in:
 *   - the root layout itself,
 *   - hydration mismatches (these tear the whole tree before any inner
 *     boundary is reached),
 *   - the RouterProvider / page-building scaffolding code.
 *
 * We deliberately omit the `fallback` prop so the boundary falls back to its
 * built-in `DefaultErrorFallback` — if a user-authored fallback crashed
 * during its own render, we'd still have a guaranteed-to-render UI here.
 * Users who want a custom *branded* global error UI author a root-level
 * `error.tsx`; that convention is already picked up by `segmentBoundaries`
 * at depth 0 and sits inside this top boundary.
 *
 * @internal Exported for unit testing only.
 */
export function buildRouterTree(
  context: RouterContextValue,
  pageElement: React.ReactNode,
  options: RootBoundaryOptions
): React.ReactElement {
  return (
    <FurinErrorBoundary {...options}>
      <RouterContext.Provider value={context}>{pageElement}</RouterContext.Provider>
    </FurinErrorBoundary>
  );
}

/**
 * Options threaded from `RouterProvider` (or a test harness) into each
 * boundary that `buildPageElement` inserts:
 *
 * - `onReset` — invoked by `FurinErrorBoundary.reset` after it clears local
 *   error state. RouterProvider wires this to `refresh()` so the user's
 *   `reset()` prop re-runs the current route's loaders in addition to
 *   remounting the subtree.
 * - `resetKey` — when it changes, both boundary classes clear their latched
 *   error. RouterProvider passes `currentHref`, so navigating between
 *   sibling routes that share a boundary (e.g. /blog/a → /blog/b) auto-clears
 *   any stuck error state even when the boundary instance persists.
 */
export interface BoundaryOptions {
  onReset?: () => void;
  resetKey?: string | number;
}

/**
 * Wraps `inner` with the client-side boundary pair declared at one depth.
 * Error boundary must be OUTSIDE the not-found boundary — see the detailed
 * justification in `render/element.tsx`'s `wrapInBoundaries`. The client
 * mirrors the server's wrap order exactly so hydration sees an identical
 * React tree.
 */
function wrapPageBoundaries(
  inner: React.ReactNode,
  segment: ClientSegmentBoundary | undefined,
  options: BoundaryOptions | undefined
): React.ReactNode {
  if (!segment) {
    return inner;
  }
  let wrapped = inner;
  if (segment.notFound) {
    wrapped = (
      <FurinNotFoundBoundary fallback={segment.notFound} resetKey={options?.resetKey}>
        {wrapped}
      </FurinNotFoundBoundary>
    );
  }
  if (segment.error) {
    wrapped = (
      <FurinErrorBoundary
        fallback={segment.error}
        onReset={options?.onReset}
        resetKey={options?.resetKey}
      >
        {wrapped}
      </FurinErrorBoundary>
    );
  }
  return wrapped;
}

/** @internal Exported for unit testing only. */
export function buildPageElement(
  match: LoadedClientRoute,
  root: RuntimeRoute | null,
  data: Record<string, unknown>,
  options: BoundaryOptions | undefined
): React.ReactNode {
  let element: React.ReactNode = createElement(match.component, data);

  // Collect non-root layouts from the route chain (bottom-up)
  const allLayouts: React.ComponentType<Record<string, unknown> & { children: React.ReactNode }>[] =
    [];
  let current: RuntimeRoute | undefined = match.pageRoute;
  while (current) {
    if (current.layout) {
      allLayouts.unshift(current.layout);
    }
    current = current.parent;
  }

  // If a root layout exists, the first entry in allLayouts IS the root — skip it here
  const layouts = root ? allLayouts.slice(1) : allLayouts;

  // Index boundaries by depth for O(1) lookup. `layouts[i]` corresponds to
  // route-chain depth `i + 1` (depth 0 = root layout, handled separately).
  const byDepth = new Map<number, ClientSegmentBoundary>();
  for (const segment of match.segmentBoundaries ?? []) {
    byDepth.set(segment.depth, segment);
  }

  // Inside-out: at each layout level wrap the subtree with its same-depth
  // boundary (so the boundary sits INSIDE the layout), then wrap with the
  // layout itself.
  for (let i = layouts.length - 1; i >= 0; i--) {
    element = wrapPageBoundaries(element, byDepth.get(i + 1), options);
    const Layout = layouts[i];
    if (Layout) {
      // biome-ignore lint/suspicious/noExplicitAny: spread loses `children` type info for createElement
      element = createElement(Layout, { ...data } as any, element);
    }
  }

  // Depth 0 boundary wraps EVERYTHING below the root layout.
  element = wrapPageBoundaries(element, byDepth.get(0), options);

  if (root?.layout) {
    // biome-ignore lint/suspicious/noExplicitAny: spread loses `children` type info for createElement
    element = createElement(root.layout, { ...data } as any, element);
  }

  return element;
}

/** Scrolls to a hash target or the top of the page after SPA navigation. */
function handleScrollRestoration(
  href: string,
  navigationToken: number,
  navVersion: { current: number }
): void {
  const destUrl = new URL(href, window.location.origin);
  if (destUrl.hash) {
    const id = decodeURIComponent(destUrl.hash.slice(1));
    const scrollToHashTarget = () => {
      if (navVersion.current !== navigationToken) {
        return;
      }

      const element = document.getElementById(id);
      if (element) {
        element.scrollIntoView({ behavior: "instant", block: "start" });
      }
    };

    window.requestAnimationFrame(() => {
      scrollToHashTarget();
      if (document.getElementById(id)) {
        return;
      }

      window.requestAnimationFrame(() => {
        scrollToHashTarget();
      });
    });
  } else {
    window.scrollTo({ top: 0, behavior: "instant" });
  }
}

// ── Scroll restoration helpers ─────────────────────────────────────────────────

const SCROLL_STORAGE_KEY = "__furin_scroll__";

function getHistoryKey(state: unknown): string | undefined {
  return (state as { _furinKey?: string } | null)?._furinKey;
}

function generateHistoryKey(): string {
  return Math.random().toString(36).slice(2, 9);
}

function saveScrollPosition(key: string): void {
  try {
    const raw = sessionStorage.getItem(SCROLL_STORAGE_KEY);
    const positions: Record<string, number> = raw ? JSON.parse(raw) : {};
    positions[key] = window.scrollY;
    const keys = Object.keys(positions);
    if (keys.length > 50) {
      delete positions[keys[0] as string];
    }
    sessionStorage.setItem(SCROLL_STORAGE_KEY, JSON.stringify(positions));
  } catch {
    // sessionStorage unavailable (private mode, quota exceeded, etc.)
  }
}

function restoreScrollPosition(key: string, token: number, version: { current: number }): void {
  try {
    const raw = sessionStorage.getItem(SCROLL_STORAGE_KEY);
    const positions: Record<string, number> = raw ? JSON.parse(raw) : {};
    const y = positions[key] ?? 0;
    window.requestAnimationFrame(() => {
      window.requestAnimationFrame(() => {
        if (version.current !== token) {
          return;
        }
        window.scrollTo({ top: y, behavior: "instant" });
      });
    });
  } catch {
    window.scrollTo({ top: 0, behavior: "instant" });
  }
}

// ── Path helpers ───────────────────────────────────────────────────────────────

/**
 * Returns `true` when the server reports a different build-id from the one
 * embedded in the initial HTML (`<meta name="furin-build-id">`). The client
 * bundle is then stale and SPA navigation would mount wrong components, so
 * the caller must force a full-page reload to pick up the new deploy.
 */
function isStaleDeployResponse(res: Response): boolean {
  const serverBuildId = res.headers.get("x-furin-build-id");
  if (!serverBuildId) {
    return false;
  }
  const metaEl =
    typeof document === "undefined"
      ? null
      : document.querySelector<HTMLMetaElement>('meta[name="furin-build-id"]');
  const clientBuildId = metaEl?.content;
  return Boolean(clientBuildId && serverBuildId !== clientBuildId);
}

/**
 * Parses the HTML payload of a page response into the pieces `fetchPageState`
 * cares about: the document (for title), the __FURIN_DATA__ loader payload,
 * and the logical `finalHref` after any server-side redirect.
 */
async function parsePageResponse(
  res: Response,
  basePath: string
): Promise<{ data: Record<string, unknown> | null; finalHref: string | undefined; title: string }> {
  let finalHref: string | undefined;
  if (res.redirected) {
    const final = new URL(res.url);
    finalHref = toLogical(final.pathname, basePath) + final.search;
  }
  const html = await res.text();
  const doc = new DOMParser().parseFromString(html, "text/html");
  const dataEl = doc.getElementById("__FURIN_DATA__");
  const data = dataEl ? JSON.parse(dataEl.textContent || "{}") : null;
  return { data, finalHref, title: doc.title };
}

/** Strips basePath prefix from a physical pathname, returning the logical path. */
function toLogical(physicalPathname: string, basePath: string): string {
  if (
    basePath &&
    physicalPathname.startsWith(basePath) &&
    // Require a path boundary after the prefix so "/furin" doesn't match "/furinity/foo"
    (physicalPathname.length === basePath.length || physicalPathname[basePath.length] === "/")
  ) {
    return physicalPathname.slice(basePath.length) || "/";
  }
  return physicalPathname;
}

export function RouterProvider({
  routes,
  root,
  initialMatch,
  initialData,
  initialDigest,
  initialNotFound,
  autoRefresh = true,
  basePath = "",
  defaultPreload = "intent",
  defaultPreloadDelay = 50,
  defaultPreloadStaleTime = 30_000,
  prefetchCacheSize = 50,
}: RouterProviderProps): React.ReactElement {
  // Initial state. When `initialMatch` is `null`, `initialNotFound` MUST be set —
  // the provider boots into the inline not-found UI (see `initialNotFound` JSDoc).
  // `notFoundBoundaries` is left undefined so the render path can fall through to
  // the memoised `rootBoundaries` below (which isn't available yet at useState init).
  const [state, setState] = useState<RouterState>(() => ({
    match: initialMatch,
    data: initialData,
    notFound: initialNotFound,
  }));
  const [isNavigating, setIsNavigating] = useState(false);
  // currentHref stores the LOGICAL path (basePath stripped) so Link active-state
  // detection works with route patterns that never include the basePath prefix.
  const [currentHref, setCurrentHref] = useState<string>(() => {
    if (typeof window === "undefined") {
      return "/";
    }
    return toLogical(window.location.pathname, basePath) + window.location.search;
  });
  const prefetchCache = useRef(new Map<string, CacheEntry>());
  /** Monotonic counter to discard stale navigations (race condition guard). */
  const navVersion = useRef(0);
  /**
   * Tracks the last successfully rendered match for use in the no-route 404 path.
   * `null` on the initial render when the URL didn't match any route and the
   * provider booted directly into the not-found state; flips to a real match as
   * soon as the user navigates away via `navigate()` or the back button.
   */
  const currentMatchRef = useRef<LoadedClientRoute | null>(initialMatch);

  /**
   * Depth-0 boundary (pagesDir root level) for the "no client route matched" 404
   * path. When an unknown URL is navigated to, the server's `renderRootNotFound`
   * handles it — the root `not-found.tsx` (depth 0) is the correct component to
   * render inline instead of doing a full-page reload.
   * Computed once per `routes` change; stable across navigations.
   */
  const rootBoundaries = useMemo<ClientSegmentBoundary[] | undefined>(() => {
    for (const route of routes) {
      const depth0 = route.segmentBoundaries?.find((b) => b.depth === 0);
      if (depth0) {
        return [depth0];
      }
    }
    return;
  }, [routes]);

  const fetchPageState = useCallback(
    async (logicalHref: string): Promise<RouterState | null> => {
      try {
        // Physical href: what the browser/server actually receives.
        // For basePath deployments: fetch("/furin/docs/routing") not fetch("/docs/routing").
        const physicalHref = basePath + logicalHref;
        const url = new URL(physicalHref, window.location.origin);
        // Route matching always uses the LOGICAL pathname (basePath stripped).
        const logicalPathname = toLogical(url.pathname, basePath);
        const match = routes.find((r) => r.regex.test(logicalPathname));
        if (!match) {
          // No client-side route matched — the server will call renderRootNotFound.
          // Fetch the URL so we can detect the __furinStatus: 404 signal embedded
          // by renderRootNotFound and render the 404 UI inline (SPA) instead of
          // forcing a jarring full-page reload.
          const res = await fetch(physicalHref);
          if (isStaleDeployResponse(res)) {
            window.location.href = physicalHref;
            return null;
          }
          const { data, finalHref, title } = await parsePageResponse(res, basePath);
          const kind = classifySpaResponse(res.status, data);
          if (kind.kind !== "not-found") {
            // Non-404 server response for an unmatched URL (e.g. 5xx) — bail to
            // full-page navigation so the browser shows whatever the server sent.
            return null;
          }
          // Strip internal signals before surfacing loader data.
          const { __furinStatus: _s, __furinNotFound: _n, ...cleanData } = data ?? {};
          return {
            match: currentMatchRef.current,
            data: cleanData,
            title,
            finalHref,
            notFound: kind.error,
            // Pass only depth-0 boundaries: for an unmatched URL the root
            // not-found.tsx is always the right component — no page-specific
            // segment context exists.
            notFoundBoundaries: rootBoundaries,
          };
        }

        // Parallelize HTML data fetch + JS chunk load for this route.
        // The browser module cache makes match.load() near-instant for already-loaded pages.
        const [res, loadedMod] = await Promise.all([fetch(physicalHref), match.load()]);

        // Stale-deploy detection: if the server reports a different buildId, the client
        // bundle is outdated and SPA navigation would mount wrong components / stale code.
        // Force a full page reload to pick up the new bundle.
        if (isStaleDeployResponse(res)) {
          window.location.href = physicalHref;
          return null;
        }

        // Parse the HTML payload BEFORE deciding whether to bail on !res.ok.
        // Slice 8: a 404 response still carries a valid __FURIN_DATA__ with a
        // `__furinStatus: 404` signal, which lets us render the not-found UI
        // inline instead of doing a jarring full-page reload. Any other
        // non-2xx still bails out (see `classifySpaResponse`).
        const { data, finalHref, title } = await parsePageResponse(res, basePath);

        const kind = classifySpaResponse(res.status, data);
        if (kind.kind === "bail") {
          log.warn({ action: "navigate_server_error", href: physicalHref, status: res.status });
          return null;
        }

        const loadedMatch: LoadedClientRoute = {
          ...match,
          component: loadedMod.default.component,
          pageRoute: loadedMod.default._route,
        };

        if (kind.kind === "not-found") {
          // Strip the server-injected signals from `data` before handing it to
          // the component — the NotFound payload is surfaced via `state.notFound`
          // instead, and leaking __furinStatus into component props would be
          // noise. The caller (RouterProvider render) ignores `data` when
          // `notFound` is set anyway, but we keep it tidy for devtools.
          const { __furinStatus, __furinNotFound, ...cleanData } = data ?? {};
          return {
            match: loadedMatch,
            data: cleanData,
            title,
            finalHref,
            notFound: kind.error,
          };
        }

        return { match: loadedMatch, data: data ?? {}, title, finalHref };
      } catch (err: unknown) {
        log.error({ action: "navigate_failed", href: basePath + logicalHref, error: String(err) });
        return null;
      }
    },
    [routes, basePath, rootBoundaries]
  );

  const invalidatePrefetch = useCallback((path: string, type: "page" | "layout" = "page") => {
    const normalizedPath = stripHashFromHref(path);

    if (type === "page") {
      for (const key of [...prefetchCache.current.keys()]) {
        if (stripHashFromHref(key) === normalizedPath) {
          prefetchCache.current.delete(key);
        }
      }
      return;
    }

    // layout: prefix match — evict the path itself and all nested children
    const prefix =
      normalizedPath === "/" || normalizedPath.endsWith("/")
        ? normalizedPath
        : `${normalizedPath}/`;
    for (const key of [...prefetchCache.current.keys()]) {
      const normalizedKey = stripHashFromHref(key);
      if (normalizedKey === normalizedPath || normalizedKey.startsWith(prefix)) {
        prefetchCache.current.delete(key);
      }
    }
  }, []);

  const prefetch = useCallback(
    (href: string, opts?: { staleTime?: number }) => {
      const staleTime = opts?.staleTime ?? defaultPreloadStaleTime;
      const existing = prefetchCache.current.get(href);
      if (existing && !shouldRefetch(existing)) {
        return;
      }
      prefetchCache.current.set(href, {
        promise: fetchPageState(href),
        createdAt: Date.now(),
        staleTime,
      });
      // Evict the oldest entry when the cap is exceeded
      if (prefetchCache.current.size > prefetchCacheSize) {
        const oldest = prefetchCache.current.keys().next().value as string;
        prefetchCache.current.delete(oldest);
      }
    },
    [fetchPageState, defaultPreloadStaleTime, prefetchCacheSize]
  );

  const navigate = useCallback(
    async (logicalHref: string, opts?: { replace?: boolean; resetScroll?: boolean }) => {
      // logicalHref is the route-relative path (no basePath).
      // The prefetch cache is keyed by logical hrefs.
      prefetch(logicalHref);
      const myVersion = ++navVersion.current;
      setIsNavigating(true);
      try {
        const newState = await prefetchCache.current.get(logicalHref)?.promise;
        // Discard if a newer navigation was started while we were waiting
        if (navVersion.current !== myVersion) {
          return;
        }
        if (!newState) {
          log.warn({
            action: "navigate_fallback",
            href: logicalHref,
            reason: "prefetch_returned_null",
          });
          // Fall back to full-page navigation using the physical URL.
          window.location.href = basePath + logicalHref;
          return;
        }
        currentMatchRef.current = newState.match;
        setState(newState);
        if (newState.title) {
          document.title = newState.title;
        }
        // effectiveHref is logical (finalHref from fetchPageState is also logical).
        const effectiveLogical = newState.finalHref ?? logicalHref;
        // Push the PHYSICAL path to browser history.
        const physicalEffective = basePath + effectiveLogical;
        if (opts?.replace) {
          // Preserve the existing key — same history entry, URL just updated.
          window.history.replaceState(
            {
              ...((history.state as object) ?? {}),
              _furinKey: getHistoryKey(history.state) ?? generateHistoryKey(),
            },
            "",
            physicalEffective
          );
        } else {
          // Save current position before leaving, then push a fresh entry.
          const currentKey = getHistoryKey(history.state);
          if (currentKey) {
            saveScrollPosition(currentKey);
          }
          window.history.pushState({ _furinKey: generateHistoryKey() }, "", physicalEffective);
        }
        // Store the LOGICAL path in currentHref so Link active-state works.
        const effectiveUrl = new URL(physicalEffective, window.location.origin);
        const logicalPath = toLogical(effectiveUrl.pathname, basePath);
        setCurrentHref(logicalPath + effectiveUrl.search);
        if (opts?.resetScroll ?? true) {
          handleScrollRestoration(physicalEffective, myVersion, navVersion);
        }
      } finally {
        // Only clear navigating flag if this is still the latest navigation
        if (navVersion.current === myVersion) {
          setIsNavigating(false);
        }
      }
    },
    [prefetch, basePath]
  );

  const refresh = useCallback(
    async (opts?: { resetScroll?: boolean }) => {
      // Convert the physical browser URL to a logical href before navigating.
      const logicalPath = toLogical(window.location.pathname, basePath);
      const logicalHref = logicalPath + window.location.search;
      // Bust the cache for this exact logical page so navigate always re-fetches
      invalidatePrefetch(logicalHref, "page");
      await navigate(logicalHref, { replace: true, resetScroll: opts?.resetScroll ?? false });
    },
    [navigate, invalidatePrefetch, basePath]
  );

  const handlePopState = useCallback(async () => {
    // Capture the destination key immediately — history.state is already the
    // destination entry when popstate fires, before any awaits.
    const destKey = getHistoryKey(history.state);
    // Convert physical browser URL to logical href for cache lookup + fetchPageState.
    const logicalPath = toLogical(window.location.pathname, basePath);
    const logicalHref = logicalPath + window.location.search;
    const myVersion = ++navVersion.current;
    setIsNavigating(true);
    try {
      // Check prefetch cache before fetching fresh (keyed by logical href)
      const cached = prefetchCache.current.get(logicalHref);
      let newState: RouterState | null;
      if (cached && !shouldRefetch(cached)) {
        newState = await cached.promise;
      } else {
        newState = await fetchPageState(logicalHref);
      }
      // Discard if a newer navigation was started while we were waiting
      if (navVersion.current !== myVersion) {
        return;
      }
      if (!newState) {
        log.warn({
          action: "popstate_fallback",
          href: logicalHref,
          reason: "fetchPageState_returned_null",
        });
        window.location.reload();
        return;
      }
      currentMatchRef.current = newState.match;
      setState(newState);
      if (newState.title) {
        document.title = newState.title;
      }
      // effectiveHref is logical (includes search); push physical to history if server redirected.
      const effectiveLogical = newState.finalHref ?? logicalHref;
      if (newState.finalHref) {
        // Preserve _furinKey so restoreScrollPosition still works after a redirect.
        window.history.replaceState(history.state, "", basePath + effectiveLogical);
      }
      // effectiveLogical already contains the search params — no URL round-trip needed.
      setCurrentHref(effectiveLogical);
      // Restore the saved scroll position for this history entry (double rAF waits
      // for React to finish painting the new page before scrolling).
      if (destKey) {
        restoreScrollPosition(destKey, myVersion, navVersion);
      } else {
        window.scrollTo({ top: 0, behavior: "instant" });
      }
    } finally {
      if (navVersion.current === myVersion) {
        setIsNavigating(false);
      }
    }
  }, [fetchPageState, basePath]);

  // Disable native scroll restoration and assign a key to the initial history entry
  useEffect(() => {
    const prevScrollRestoration = history.scrollRestoration;
    history.scrollRestoration = "manual";
    if (!getHistoryKey(history.state)) {
      history.replaceState(
        { ...((history.state as object) ?? {}), _furinKey: generateHistoryKey() },
        ""
      );
    }
    return () => {
      history.scrollRestoration = prevScrollRestoration;
    };
  }, []);

  // Handle browser back/forward
  useEffect(() => {
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, [handlePopState]);

  // Intercept all window.fetch calls to auto-process X-Furin-Revalidate headers.
  // This ensures that API routes calling revalidatePath() automatically bust the
  // client prefetch cache, even for non-navigation fetches (e.g. form submissions).
  // When autoRefresh=true (default), also re-fetches the current page if it was invalidated.
  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    const originalFetch = window.fetch;
    const wrapped = async (...args: Parameters<typeof fetch>): Promise<Response> => {
      const response = await originalFetch.apply(window, args);
      const invalidated: Array<{ path: string; type: "page" | "layout" }> = [];
      applyRevalidateHeader(response.headers, (path, type = "page") => {
        invalidatePrefetch(path, type);
        invalidated.push({ path, type });
      });
      if (autoRefresh && invalidated.length > 0) {
        const currentPath = window.location.pathname + window.location.search;
        if (shouldAutoRefreshPath(currentPath, invalidated)) {
          // fire-and-forget: don't block the original fetch caller
          refresh();
        }
      }
      return response;
    };
    // Copy static fetch methods (e.g. preconnect) so the patched value satisfies typeof fetch.
    Object.assign(wrapped, originalFetch);
    // biome-ignore lint/suspicious/noExplicitAny: Object.assign copies all static props but TS can't infer it
    window.fetch = wrapped as any;
    return () => {
      window.fetch = originalFetch;
    };
  }, [invalidatePrefetch, refresh, autoRefresh]);

  // Slice 8 — when a prior SPA navigation hit a loader-thrown or catch-all 404,
  // render the bare not-found element (mirrors server's `buildNotFoundElement`).
  // - `notFoundBoundaries`: set when no route matched (always depth-0 / root
  //   not-found.tsx, since no page-specific context applies to unknown URLs).
  // - Fallback to `match.segmentBoundaries`: set when a matched loader called
  //   `notFound()` (preserves the deepest route-level not-found.tsx).
  // - Fallback to `rootBoundaries`: the initial-hydration "direct load to an
  //   unknown URL" case, where `state.match` is null because no client route
  //   matched the boot URL. The provider booted into not-found mode to give
  //   Links in the not-found UI a live RouterContext (so "Go Home" does SPA
  //   navigation, not a full reload).
  // The render path is split explicitly rather than collapsed into a ternary
  // so TypeScript can narrow `state.match` to non-null for `buildPageElement`
  // — the invariant is "`state.match` is null only when `state.notFound` is set".
  let pageElement: React.ReactNode;
  if (state.notFound || !state.match) {
    pageElement = buildNotFoundPageElement(
      state.notFoundBoundaries ?? state.match?.segmentBoundaries ?? rootBoundaries,
      state.notFound ?? {}
    );
  } else {
    pageElement = buildPageElement(state.match, root, state.data, {
      // User's `reset()` prop → clear local boundary state (handled by the
      // boundary itself) → re-run loaders for the current route so transient
      // errors (bad state, expired data) can recover without a full reload.
      onReset: refresh,
      // Auto-clear latched errors when navigating between routes that share
      // a boundary instance — otherwise the new route would render INSIDE
      // the previous route's error fallback.
      resetKey: currentHref,
    });
  }

  // Slice 9 + 10 — wrap the entire tree in a root FurinErrorBoundary that
  // catches anything per-segment boundaries missed (root layout crash,
  // hydration mismatch, scaffolding errors). `digest` is seeded from the
  // server's __FURIN_DATA__.__furinError.digest so client fallback UIs show
  // the same id the server already logged.
  return buildRouterTree(
    {
      basePath,
      currentHref,
      navigate,
      prefetch,
      refresh,
      invalidatePrefetch,
      isNavigating,
      defaultPreload,
      defaultPreloadDelay,
      defaultPreloadStaleTime,
    },
    pageElement,
    {
      digest: initialDigest,
      onReset: refresh,
      resetKey: currentHref,
    }
  );
}

// ── Link ───────────────────────────────────────────────────────────────────────

interface LinkView {
  extraProps: React.AnchorHTMLAttributes<HTMLAnchorElement>;
  href: string;
  isActive: boolean;
  logicalHref: string;
  resolvedChildren: React.ReactNode;
}

/**
 * Shared href/active-state/props computation used by both LinkInteractive (CSR)
 * and renderLinkElement (SSR). Centralising this keeps the two render paths in sync.
 */
function computeLinkView<To extends RouteTo>(
  {
    to,
    search,
    hash,
    children,
    activeProps,
    inactiveProps,
  }: Pick<LinkProps<To>, "to" | "search" | "hash" | "children" | "activeProps" | "inactiveProps">,
  router: RouterContextValue
): LinkView {
  const logicalHref = buildHref(
    to as string,
    search as Record<string, unknown> | null | undefined,
    hash
  );
  const logicalHrefWithoutHash = buildHref(
    to as string,
    search as Record<string, unknown> | null | undefined,
    undefined
  );
  const href = router.basePath + logicalHref;
  const isActive = router.currentHref === logicalHrefWithoutHash;
  const resolvedChildren = typeof children === "function" ? children({ isActive }) : children;
  const extraProps: React.AnchorHTMLAttributes<HTMLAnchorElement> = {
    ...(inactiveProps && !isActive ? inactiveProps() : {}),
    ...(activeProps ? activeProps({ isActive }) : {}),
  };
  return { logicalHref, href, isActive, resolvedChildren, extraProps };
}

/**
 * Full interactive Link — only rendered on the client where hooks are safe.
 * Never rendered during SSR so it's immune to duplicate-React-instance issues
 * that can arise when page modules are loaded via the furin-dev-page virtual
 * namespace (Bun HMR).
 */
function LinkInteractive<To extends RouteTo>({
  to,
  search,
  hash,
  preload,
  preloadDelay,
  preloadStaleTime,
  replace,
  disabled,
  resetScroll,
  activeProps,
  inactiveProps,
  onClick,
  onMouseEnter,
  onMouseLeave,
  onFocus,
  children,
  ...anchorProps
}: LinkProps<To>): React.ReactElement {
  const router = useRouter();
  const anchorRef = useRef<HTMLAnchorElement>(null);
  const intentTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // logicalHref: route-relative path (no basePath), used for navigation + active state.
  // physicalHref (href): what the browser sees — basePath + logicalHref.
  const { logicalHref, href, isActive, resolvedChildren, extraProps } = computeLinkView(
    { to, search, hash, children, activeProps, inactiveProps },
    router
  );

  const effectivePreload = preload ?? router.defaultPreload;
  const effectiveDelay = preloadDelay ?? router.defaultPreloadDelay;
  const effectiveStaleTime = preloadStaleTime ?? router.defaultPreloadStaleTime;

  const triggerPrefetch = useCallback(() => {
    // prefetch() expects the logical href (no basePath prefix).
    router.prefetch(logicalHref, { staleTime: effectiveStaleTime });
  }, [router, logicalHref, effectiveStaleTime]);

  // "render": preload immediately on mount
  useEffect(() => {
    if (effectivePreload === "render") {
      triggerPrefetch();
    }
  }, [effectivePreload, triggerPrefetch]);

  // "viewport": preload when link enters viewport
  useEffect(() => {
    if (effectivePreload !== "viewport" || !anchorRef.current) {
      return;
    }
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry?.isIntersecting) {
          triggerPrefetch();
          observer.disconnect();
        }
      },
      { rootMargin: "200px" }
    );
    observer.observe(anchorRef.current);
    return () => observer.disconnect();
  }, [effectivePreload, triggerPrefetch]);

  const isInternal = (url: string): boolean => {
    try {
      return new URL(url, window.location.origin).origin === window.location.origin;
    } catch {
      return false;
    }
  };

  const handleClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onClick?.(e);
    if (e.defaultPrevented || disabled) {
      return;
    }
    // Let browser handle modifier+click (new tab, etc.)
    if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) {
      return;
    }
    // Let browser handle non-self targets (e.g. target="_blank")
    if (anchorProps.target && anchorProps.target !== "_self") {
      return;
    }
    // Let browser handle external links
    if (!isInternal(href)) {
      return;
    }
    e.preventDefault();
    // navigate() expects the logical href (no basePath prefix).
    router.navigate(logicalHref, { replace, resetScroll: resetScroll ?? true });
  };

  const handleMouseEnter = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onMouseEnter?.(e);
    if (!disabled && effectivePreload === "intent" && isInternal(href)) {
      intentTimerRef.current = setTimeout(triggerPrefetch, effectiveDelay);
    }
  };

  const handleMouseLeave = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onMouseLeave?.(e);
    if (intentTimerRef.current !== null) {
      clearTimeout(intentTimerRef.current);
      intentTimerRef.current = null;
    }
  };

  const handleFocus = (e: React.FocusEvent<HTMLAnchorElement>) => {
    onFocus?.(e);
    if (!disabled && effectivePreload === "intent" && isInternal(href)) {
      triggerPrefetch();
    }
  };

  return createElement(
    "a",
    {
      ref: anchorRef,
      href,
      onClick: handleClick,
      onMouseEnter: handleMouseEnter,
      onMouseLeave: handleMouseLeave,
      onFocus: handleFocus,
      ...(isActive ? { "data-status": "active" } : {}),
      ...anchorProps,
      ...extraProps,
      ...(disabled ? { "aria-disabled": true } : {}),
    },
    resolvedChildren
  );
}

// ── SSR fallback router ────────────────────────────────────────────────────────

/**
 * Static fallback used by Link during SSR when there is no RouterProvider.
 * Must not reference `window` — this object is created at module parse time.
 */
const SSR_FALLBACK_ROUTER: RouterContextValue = {
  basePath: "",
  currentHref: "/",
  navigate: () => Promise.resolve(),
  prefetch: () => {
    /* noop */
  },
  invalidatePrefetch: () => {
    /* noop */
  },
  refresh: () => Promise.resolve(),
  isNavigating: false,
  defaultPreload: "intent",
  defaultPreloadDelay: 50,
  defaultPreloadStaleTime: 30_000,
};

/**
 * Pure render helper — no hooks, safe to call from any context including SSR.
 * Computes href, active state, and applies activeProps / inactiveProps before
 * returning the final `<a>` element.
 */
function renderLinkElement<To extends RouteTo>(
  props: LinkProps<To>,
  router: RouterContextValue
): React.ReactElement {
  const { href, isActive, resolvedChildren, extraProps } = computeLinkView(props, router);

  // Destructure to strip Link-specific and client-only props before spreading onto <a>.
  const {
    to: _to,
    search: _search,
    hash: _hash,
    children: _children,
    activeProps: _ap,
    inactiveProps: _ip,
    disabled,
    preload: _p,
    preloadDelay: _pd,
    preloadStaleTime: _ps,
    replace: _r,
    resetScroll: _rs,
    onClick: _oc,
    onMouseEnter: _ome,
    onMouseLeave: _oml,
    onFocus: _of,
    ...anchorProps
  } = props;

  return createElement(
    "a",
    {
      href,
      ...(isActive ? { "data-status": "active" } : {}),
      ...anchorProps,
      ...extraProps,
      ...(disabled ? { "aria-disabled": true } : {}),
    },
    resolvedChildren
  );
}

/**
 * SSR-aware Link component.
 *
 * - **Server (SSR):** uses `RouterContext.Consumer` (a render-prop, not a hook)
 *   to read basePath / currentHref from any enclosing RouterProvider, then
 *   falls back to `SSR_FALLBACK_ROUTER` when no provider is present.
 *   `Context.Consumer` bypasses `ReactCurrentDispatcher` entirely, so it is
 *   safe even when two React instances coexist in the module graph (Bun HMR).
 * - **Client:** delegates to `LinkInteractive` which adds preloading, SPA
 *   navigation, active-state tracking and all other interactive features.
 */
export function Link<To extends RouteTo>(props: LinkProps<To>): React.ReactElement {
  if (typeof window === "undefined") {
    // Use Context.Consumer instead of useContext — the Consumer is processed
    // by react-dom/server directly (no dispatcher lookup), so it works even
    // when link.tsx is loaded under a second React instance via the
    // furin-dev-page virtual namespace after a Bun HMR reload.
    return createElement(RouterContext.Consumer, {
      // biome-ignore lint/correctness/noChildrenProp: render-prop pattern requires children-as-function
      children: (routerCtx: RouterContextValue | null) =>
        renderLinkElement(props, routerCtx ?? SSR_FALLBACK_ROUTER),
    });
  }

  // ── Client rendering ──────────────────────────────────────────────────────
  return createElement(
    LinkInteractive as React.ComponentType<LinkProps<RouteTo>>,
    props as LinkProps<RouteTo>
  );
}
