import { log } from "evlog";
import type React from "react";
import {
  createContext,
  createElement,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
} from "react";
import type { RuntimeRoute } from "./client";

// ── Types ─────────────────────────────────────────────────────────────────────

/**
 * Augment this interface via declaration merging in furin-env.d.ts
 * to get type-safe `to` autocompletion and per-route `search` types on <Link>.
 *
 * @example
 * // furin-env.d.ts (auto-generated by Furin at project root)
 * import "@teyik0/furin/link";
 * declare module "@teyik0/furin/link" {
 *   interface RouteManifest {
 *     "/blog": { search?: { page?: number; tag?: string } };
 *     "/":     { search?: never };
 *     [key: `/blog/${string}`]: { search?: never };
 *   }
 * }
 */
// biome-ignore lint/suspicious/noEmptyInterface: intentionally augmentable via furin-env.d.ts
export interface RouteManifest {}

/**
 * The valid `to` pathname union derived from the augmented RouteManifest.
 * Falls back to `string` when furin-env.d.ts has not been generated yet.
 */
export type RouteTo = keyof RouteManifest extends never ? string : keyof RouteManifest;

/**
 * The typed search params for a given `to` pathname.
 * Falls back to a permissive record when RouteManifest is not augmented.
 */
export type RouteSearch<To extends RouteTo> = keyof RouteManifest extends never
  ? Record<string, string | number | boolean | null | undefined>
  : To extends keyof RouteManifest
    ? RouteManifest[To] extends { search?: infer S }
      ? S
      : undefined
    : undefined;

export type PreloadStrategy = false | "intent" | "viewport" | "render";

export interface LinkProps<To extends RouteTo = RouteTo>
  extends Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, "href"> {
  /** Optional URL fragment (without the #). */
  hash?: string;
  /** Preload strategy. Default: "intent" (preload on hover/focus). */
  preload?: PreloadStrategy;
  /** Delay in ms before intent preload triggers. Default: 50. */
  preloadDelay?: number;
  /** How long a preloaded entry stays fresh (ms). Default: 30_000. */
  preloadStaleTime?: number;
  /** Typed search params for this route. Auto-completed from the route's query schema. */
  search?: RouteSearch<To>;
  to: To;
}

/**
 * Builds a full href string from a pathname, optional search params, and optional hash.
 * Null/undefined search values are omitted.
 *
 * @internal Exported for unit testing only.
 */
export function buildHref(
  to: string,
  search?: Record<string, unknown> | null,
  hash?: string
): string {
  let url = to;
  if (search && Object.keys(search).length > 0) {
    const params = new URLSearchParams();
    for (const [k, v] of Object.entries(search)) {
      if (v != null) {
        params.set(k, String(v));
      }
    }
    const qs = params.toString();
    if (qs) {
      url += `?${qs}`;
    }
  }
  if (hash) {
    url += `#${hash}`;
  }
  return url;
}

// ── Router context ─────────────────────────────────────────────────────────────

export interface RouterContextValue {
  defaultPreload: PreloadStrategy;
  defaultPreloadDelay: number;
  defaultPreloadStaleTime: number;
  isNavigating: boolean;
  navigate: (href: string, opts?: { replace?: boolean }) => Promise<void>;
  prefetch: (href: string, opts?: { staleTime?: number }) => void;
}

export const RouterContext = createContext<RouterContextValue | null>(null);

/**
 * Returns the current router context.
 * Provides a graceful fallback (full-page navigation) when used outside RouterProvider.
 */
export function useRouter(): RouterContextValue {
  return (
    useContext(RouterContext) ?? {
      navigate: (href) => {
        window.location.href = href;
        return Promise.resolve();
      },
      prefetch: () => {
        /* noop fallback */
      },
      isNavigating: false,
      defaultPreload: "intent",
      defaultPreloadDelay: 50,
      defaultPreloadStaleTime: 30_000,
    }
  );
}

// ── RouterProvider ─────────────────────────────────────────────────────────────

export interface ClientRoute {
  component?: React.ComponentType<Record<string, unknown>>;
  load: () => Promise<{
    default: { component: React.ComponentType<Record<string, unknown>>; _route: RuntimeRoute };
  }>;
  pageRoute?: RuntimeRoute;
  pattern: string;
  regex: RegExp;
}

/**
 * A ClientRoute that has been loaded — component and pageRoute are guaranteed defined.
 * The initial route is eagerly loaded in the hydrate entry; subsequent routes are loaded
 * on navigation via fetchPageState.
 */
export type LoadedClientRoute = ClientRoute & {
  component: React.ComponentType<Record<string, unknown>>;
  pageRoute: RuntimeRoute;
};

export interface RouterProviderProps {
  defaultPreload?: PreloadStrategy;
  defaultPreloadDelay?: number;
  defaultPreloadStaleTime?: number;
  initialData: Record<string, unknown>;
  initialMatch: LoadedClientRoute;
  /** Maximum number of prefetch cache entries. Oldest entry is evicted when exceeded. Default: 50. */
  prefetchCacheSize?: number;
  root: RuntimeRoute | null;
  routes: ClientRoute[];
}

interface RouterState {
  data: Record<string, unknown>;
  match: LoadedClientRoute;
  title?: string;
}

/** @internal */
export interface CacheEntry {
  createdAt: number;
  promise: Promise<RouterState | null>;
}

/** @internal Exported for unit testing only. */
export function shouldRefetch(entry: CacheEntry, staleTime: number): boolean {
  return Date.now() - entry.createdAt > staleTime;
}

/** @internal Exported for unit testing only. */
export function buildPageElement(
  match: LoadedClientRoute,
  root: RuntimeRoute | null,
  data: Record<string, unknown>
): React.ReactNode {
  let element: React.ReactNode = createElement(match.component, data);

  // Collect non-root layouts from the route chain (bottom-up)
  const allLayouts: React.ComponentType<Record<string, unknown> & { children: React.ReactNode }>[] =
    [];
  let current: RuntimeRoute | undefined = match.pageRoute;
  while (current) {
    if (current.layout) {
      allLayouts.unshift(current.layout);
    }
    current = current.parent;
  }

  // If a root layout exists, the first entry in allLayouts IS the root — skip it here
  const layouts = root ? allLayouts.slice(1) : allLayouts;

  for (let i = layouts.length - 1; i >= 0; i--) {
    const Layout = layouts[i];
    if (Layout) {
      // biome-ignore lint/suspicious/noExplicitAny: spread loses `children` type info for createElement
      element = createElement(Layout, { ...data } as any, element);
    }
  }

  if (root?.layout) {
    // biome-ignore lint/suspicious/noExplicitAny: spread loses `children` type info for createElement
    element = createElement(root.layout, { ...data } as any, element);
  }

  return element;
}

export function RouterProvider({
  routes,
  root,
  initialMatch,
  initialData,
  defaultPreload = "intent",
  defaultPreloadDelay = 50,
  defaultPreloadStaleTime = 30_000,
  prefetchCacheSize = 50,
}: RouterProviderProps): React.ReactElement {
  const [state, setState] = useState<RouterState>({
    match: initialMatch,
    data: initialData,
  });
  const [isNavigating, setIsNavigating] = useState(false);
  const prefetchCache = useRef(new Map<string, CacheEntry>());

  const fetchPageState = useCallback(
    async (href: string): Promise<RouterState | null> => {
      try {
        const url = new URL(href, window.location.origin);
        const match = routes.find((r) => r.regex.test(url.pathname));
        if (!match) {
          return null;
        }

        // Parallelize HTML data fetch + JS chunk load for this route.
        // The browser module cache makes match.load() near-instant for already-loaded pages.
        const [res, loadedMod] = await Promise.all([fetch(href), match.load()]);

        const html = await res.text();
        const doc = new DOMParser().parseFromString(html, "text/html");

        const dataEl = doc.getElementById("__FURIN_DATA__");
        const data = dataEl ? JSON.parse(dataEl.textContent || "{}") : {};

        const loadedMatch: LoadedClientRoute = {
          ...match,
          component: loadedMod.default.component,
          pageRoute: loadedMod.default._route,
        };

        return { match: loadedMatch, data, title: doc.title };
      } catch (err: unknown) {
        log.error({ action: "navigate_failed", href, error: String(err) });
        return null;
      }
    },
    [routes]
  );

  const prefetch = useCallback(
    (href: string, opts?: { staleTime?: number }) => {
      const staleTime = opts?.staleTime ?? defaultPreloadStaleTime;
      const existing = prefetchCache.current.get(href);
      if (existing && !shouldRefetch(existing, staleTime)) {
        return;
      }
      prefetchCache.current.set(href, {
        promise: fetchPageState(href),
        createdAt: Date.now(),
      });
      // Evict the oldest entry when the cap is exceeded
      if (prefetchCache.current.size > prefetchCacheSize) {
        const oldest = prefetchCache.current.keys().next().value as string;
        prefetchCache.current.delete(oldest);
      }
    },
    [fetchPageState, defaultPreloadStaleTime, prefetchCacheSize]
  );

  const navigate = useCallback(
    async (href: string, opts?: { replace?: boolean }) => {
      prefetch(href);
      setIsNavigating(true);
      try {
        const newState = await prefetchCache.current.get(href)?.promise;
        if (!newState) {
          log.warn({ action: "navigate_fallback", href, reason: "prefetch_returned_null" });
          window.location.href = href;
          return;
        }
        setState(newState);
        if (newState.title) {
          document.title = newState.title;
        }
        if (opts?.replace) {
          window.history.replaceState(null, "", href);
        } else {
          window.history.pushState(null, "", href);
        }
        window.scrollTo(0, 0);
      } finally {
        setIsNavigating(false);
      }
    },
    [prefetch]
  );

  const handlePopState = useCallback(async () => {
    const href = window.location.pathname + window.location.search;
    setIsNavigating(true);
    try {
      const newState = await fetchPageState(href);
      if (!newState) {
        log.warn({ action: "popstate_fallback", href, reason: "fetchPageState_returned_null" });
        window.location.reload();
        return;
      }
      setState(newState);
      if (newState.title) {
        document.title = newState.title;
      }
      // No scrollTo(0, 0) — browser handles scroll restoration
      // No history.pushState/replaceState — URL already updated by browser
    } finally {
      setIsNavigating(false);
    }
  }, [fetchPageState]);

  // Handle browser back/forward
  useEffect(() => {
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, [handlePopState]);

  return createElement(
    RouterContext.Provider,
    {
      value: {
        navigate,
        prefetch,
        isNavigating,
        defaultPreload,
        defaultPreloadDelay,
        defaultPreloadStaleTime,
      },
    },
    buildPageElement(state.match, root, state.data)
  ) as React.ReactElement;
}

// ── Link ───────────────────────────────────────────────────────────────────────

export function Link<To extends RouteTo>({
  to,
  search,
  hash,
  preload,
  preloadDelay,
  preloadStaleTime,
  onClick,
  onMouseEnter,
  onMouseLeave,
  onFocus,
  children,
  ...anchorProps
}: LinkProps<To>): React.ReactElement {
  const router = useRouter();
  const anchorRef = useRef<HTMLAnchorElement>(null);
  const intentTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const href = buildHref(to as string, search as Record<string, unknown> | null | undefined, hash);

  const effectivePreload = preload ?? router.defaultPreload;
  const effectiveDelay = preloadDelay ?? router.defaultPreloadDelay;
  const effectiveStaleTime = preloadStaleTime ?? router.defaultPreloadStaleTime;

  const triggerPrefetch = useCallback(() => {
    router.prefetch(href, { staleTime: effectiveStaleTime });
  }, [router, href, effectiveStaleTime]);

  // "render": preload immediately on mount
  useEffect(() => {
    if (effectivePreload === "render") {
      triggerPrefetch();
    }
  }, [effectivePreload, triggerPrefetch]);

  // "viewport": preload when link enters viewport
  useEffect(() => {
    if (effectivePreload !== "viewport" || !anchorRef.current) {
      return;
    }
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry?.isIntersecting) {
          triggerPrefetch();
          observer.disconnect();
        }
      },
      { rootMargin: "200px" }
    );
    observer.observe(anchorRef.current);
    return () => observer.disconnect();
  }, [effectivePreload, triggerPrefetch]);

  const isInternal = (url: string): boolean => {
    try {
      return new URL(url, window.location.origin).origin === window.location.origin;
    } catch {
      return false;
    }
  };

  const handleClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onClick?.(e);
    if (e.defaultPrevented) {
      return;
    }
    // Let browser handle modifier+click (new tab, etc.)
    if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) {
      return;
    }
    // Let browser handle non-self targets (e.g. target="_blank")
    if (anchorProps.target && anchorProps.target !== "_self") {
      return;
    }
    // Let browser handle external links
    if (!isInternal(href)) {
      return;
    }
    e.preventDefault();
    router.navigate(href);
  };

  const handleMouseEnter = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onMouseEnter?.(e);
    if (effectivePreload === "intent" && isInternal(href)) {
      intentTimerRef.current = setTimeout(triggerPrefetch, effectiveDelay);
    }
  };

  const handleMouseLeave = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onMouseLeave?.(e);
    if (intentTimerRef.current !== null) {
      clearTimeout(intentTimerRef.current);
      intentTimerRef.current = null;
    }
  };

  const handleFocus = (e: React.FocusEvent<HTMLAnchorElement>) => {
    onFocus?.(e);
    if (effectivePreload === "intent" && isInternal(href)) {
      triggerPrefetch();
    }
  };

  return createElement(
    "a",
    {
      ref: anchorRef,
      href,
      onClick: handleClick,
      onMouseEnter: handleMouseEnter,
      onMouseLeave: handleMouseLeave,
      onFocus: handleFocus,
      ...anchorProps,
    },
    children
  );
}
