import { log } from "evlog";
import type React from "react";
import {
  createContext,
  createElement,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
} from "react";
import type { RuntimeRoute } from "./client";

// ── Types ─────────────────────────────────────────────────────────────────────

/**
 * Augment this interface via declaration merging in furin-env.d.ts
 * to get type-safe `to` autocompletion and per-route `search` types on <Link>.
 *
 * @example
 * // furin-env.d.ts (auto-generated by Furin at project root)
 * import "@teyik0/furin/link";
 * declare module "@teyik0/furin/link" {
 *   interface RouteManifest {
 *     "/blog": { search?: { page?: number; tag?: string } };
 *     "/":     { search?: never };
 *     [key: `/blog/${string}`]: { search?: never };
 *   }
 * }
 */
// biome-ignore lint/suspicious/noEmptyInterface: intentionally augmentable via furin-env.d.ts
export interface RouteManifest {}

/**
 * The valid `to` pathname union derived from the augmented RouteManifest.
 * Falls back to `string` when furin-env.d.ts has not been generated yet.
 * When augmented, also includes `https://` and `http://` for external links.
 */
export type RouteTo = keyof RouteManifest extends never
  ? string
  : keyof RouteManifest | `https://${string}` | `http://${string}`;

/**
 * The typed search params for a given `to` pathname.
 * Falls back to a permissive record when RouteManifest is not augmented.
 */
export type RouteSearch<To extends RouteTo> = keyof RouteManifest extends never
  ? Record<string, string | number | boolean | null | undefined>
  : To extends keyof RouteManifest
    ? RouteManifest[To] extends { search?: infer S }
      ? S
      : undefined
    : undefined;

export type PreloadStrategy = false | "intent" | "viewport" | "render";

export interface LinkProps<To extends RouteTo = RouteTo>
  extends Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, "href" | "children"> {
  /**
   * Extra props merged onto the anchor when the link is active.
   * `isActive` is also passed so one function can handle both states.
   * Styles and classNames from `activeProps` win over the static props.
   */
  activeProps?: (opts: { isActive: boolean }) => React.AnchorHTMLAttributes<HTMLAnchorElement>;
  /** Static children or a render function receiving active state. */
  children?: React.ReactNode | ((state: { isActive: boolean }) => React.ReactNode);
  /** Prevents navigation and prefetch; adds aria-disabled="true". The href stays intact for right-click. */
  disabled?: boolean;
  /** Optional URL fragment (without the #). */
  hash?: string;
  /**
   * Extra props merged onto the anchor when the link is NOT active.
   * Styles and classNames from `inactiveProps` win over the static props.
   */
  inactiveProps?: () => React.AnchorHTMLAttributes<HTMLAnchorElement>;
  /** Preload strategy. Default: "intent" (preload on hover/focus). */
  preload?: PreloadStrategy;
  /** Delay in ms before intent preload triggers. Default: 50. */
  preloadDelay?: number;
  /** How long a preloaded entry stays fresh (ms). Default: 30_000. */
  preloadStaleTime?: number;
  /** If true, uses history.replaceState instead of pushState (no new history entry). */
  replace?: boolean;
  /**
   * Whether to scroll after SPA navigation. Default: true.
   * - If the destination href has a `#hash`, scrolls to that element.
   * - Otherwise scrolls to the top of the page.
   * Set to `false` to suppress all scroll behaviour (e.g. tab/drawer navigation).
   */
  resetScroll?: boolean;
  /** Typed search params for this route. Auto-completed from the route's query schema. */
  search?: RouteSearch<To>;
  to: To;
}

/**
 * Builds a full href string from a pathname, optional search params, and optional hash.
 * Null/undefined search values are omitted.
 *
 * @internal Exported for unit testing only.
 */
export function buildHref(
  to: string,
  search?: Record<string, unknown> | null,
  hash?: string
): string {
  let url = to;
  if (search && Object.keys(search).length > 0) {
    const params = new URLSearchParams();
    for (const [k, v] of Object.entries(search)) {
      if (v != null) {
        params.set(k, String(v));
      }
    }
    const qs = params.toString();
    if (qs) {
      url += `?${qs}`;
    }
  }
  if (hash) {
    url += `#${hash}`;
  }
  return url;
}

// ── Revalidation helpers ────────────────────────────────────────────────────────

/**
 * Parses the `X-Furin-Revalidate` response header and calls `invalidate` for
 * each path entry. Header format: `"/path1,/path2:layout,/path3"`
 *
 * Intended to be called from a `window.fetch` interceptor or SPA navigation
 * handler so that client-side prefetch caches are busted automatically whenever
 * a server-side `revalidatePath()` call is made within the same request.
 *
 * @example
 * ```ts
 * const res = await fetch("/api/publish");
 * applyRevalidateHeader(res.headers, (path, type) => {
 *   console.log("invalidate", path, type);
 * });
 * ```
 */
export function applyRevalidateHeader(
  headers: Headers,
  invalidate: (path: string, type?: "page" | "layout") => void
): void {
  const headerValue = headers.get("x-furin-revalidate");
  if (!headerValue) {
    return;
  }
  for (const entry of headerValue.split(",")) {
    const trimmed = entry.trim();
    if (!trimmed) {
      continue;
    }
    if (trimmed.endsWith(":layout")) {
      invalidate(trimmed.slice(0, -":layout".length), "layout");
    } else {
      invalidate(trimmed, "page");
    }
  }
}

// ── Auto-refresh helpers ───────────────────────────────────────────────────────

/**
 * Returns `true` when `currentPath` is targeted by at least one invalidation entry,
 * using the same matching rules as `invalidatePrefetch`:
 * - `type: 'page'` — exact pathname match (query string stripped)
 * - `type: 'layout'` — prefix match: the path itself OR any descendant
 *
 * @internal Exported for unit testing only.
 */
export function shouldAutoRefreshPath(
  currentPath: string,
  invalidations: ReadonlyArray<{ path: string; type: "page" | "layout" }>
): boolean {
  // Strip query string for comparison — revalidatePath works on pathnames
  const normalizedCurrent = currentPath.split("?")[0] ?? currentPath;
  return invalidations.some(({ path, type }) => {
    if (type === "page") {
      return path === normalizedCurrent;
    }
    // layout: match the path itself and all descendants
    const prefix = path === "/" || path.endsWith("/") ? path : `${path}/`;
    return normalizedCurrent === path || normalizedCurrent.startsWith(prefix);
  });
}

// ── Router context ─────────────────────────────────────────────────────────────

export interface RouterContextValue {
  /**
   * Sub-path prefix for static deployments (e.g. "/furin").
   * Empty string when the site is served from root.
   * Used by `Link` to build correct physical hrefs for the `<a>` element.
   */
  basePath: string;
  /** Current **logical** pathname + search (basePath stripped). Used by Link for active-state detection. */
  currentHref: string;
  defaultPreload: PreloadStrategy;
  defaultPreloadDelay: number;
  defaultPreloadStaleTime: number;
  /**
   * Evicts one or more prefetch cache entries, mirroring a `revalidatePath()` call
   * made on the server. Called automatically by the `window.fetch` interceptor when
   * the server emits `X-Furin-Revalidate` headers.
   *
   * - `type: 'page'` (default) — exact URL match
   * - `type: 'layout'` — prefix match (path + all nested children)
   */
  invalidatePrefetch: (path: string, type?: "page" | "layout") => void;
  isNavigating: boolean;
  navigate: (href: string, opts?: { replace?: boolean; resetScroll?: boolean }) => Promise<void>;
  prefetch: (href: string, opts?: { staleTime?: number }) => void;
  /**
   * Re-fetches the current page in-place: busts the prefetch cache entry, re-runs
   * loaders, and updates the rendered tree — without adding a history entry or
   * resetting scroll (unless `resetScroll: true` is passed).
   *
   * Prefer this over `navigate(window.location.pathname)` after a mutation.
   *
   * @example
   * ```tsx
   * const { refresh } = useRouter();
   * await apiClient.api.boards.post({ name });
   * await refresh();
   * ```
   */
  refresh: (opts?: { resetScroll?: boolean }) => Promise<void>;
}

export const RouterContext = createContext<RouterContextValue | null>(null);

/**
 * Returns the current router context.
 * Provides a graceful fallback (full-page navigation) when used outside RouterProvider.
 */
export function useRouter(): RouterContextValue {
  return (
    useContext(RouterContext) ?? {
      basePath: "",
      // Use the same "/" as SSR_FALLBACK_ROUTER so SSR and client render the
      // same active-state when no RouterProvider is present, avoiding hydration mismatches.
      currentHref: "/",
      navigate: (href) => {
        window.location.href = href;
        return Promise.resolve();
      },
      prefetch: () => {
        /* noop fallback */
      },
      invalidatePrefetch: () => {
        /* noop fallback */
      },
      refresh: () => {
        window.location.reload();
        return Promise.resolve();
      },
      isNavigating: false,
      defaultPreload: "intent",
      defaultPreloadDelay: 50,
      defaultPreloadStaleTime: 30_000,
    }
  );
}

// ── RouterProvider ─────────────────────────────────────────────────────────────

export interface ClientRoute {
  component?: React.ComponentType<Record<string, unknown>>;
  load: () => Promise<{
    default: { component: React.ComponentType<Record<string, unknown>>; _route: RuntimeRoute };
  }>;
  pageRoute?: RuntimeRoute;
  pattern: string;
  regex: RegExp;
}

/**
 * A ClientRoute that has been loaded — component and pageRoute are guaranteed defined.
 * The initial route is eagerly loaded in the hydrate entry; subsequent routes are loaded
 * on navigation via fetchPageState.
 */
export type LoadedClientRoute = ClientRoute & {
  component: React.ComponentType<Record<string, unknown>>;
  pageRoute: RuntimeRoute;
};

export interface RouterProviderProps {
  /**
   * When `true` (default), the router automatically re-fetches the current page
   * whenever a server `revalidatePath()` call targets it. The signal is the
   * `X-Furin-Revalidate` header detected on any `window.fetch` response.
   *
   * Set to `false` to opt out and call `router.refresh()` manually instead.
   */
  autoRefresh?: boolean;
  /**
   * Sub-path prefix for static deployments (e.g. "/furin").
   * Must start with "/" and have no trailing slash.
   * Default: "" (site served from root).
   *
   * When set:
   * - `currentHref` stores **logical** paths (prefix stripped) for correct active-state detection.
   * - `navigate(logicalHref)` pushes `basePath + logicalHref` to browser history.
   * - `fetch` calls use the physical path `basePath + logicalHref`.
   */
  basePath?: string;
  defaultPreload?: PreloadStrategy;
  defaultPreloadDelay?: number;
  defaultPreloadStaleTime?: number;
  initialData: Record<string, unknown>;
  initialMatch: LoadedClientRoute;
  /** Maximum number of prefetch cache entries. Oldest entry is evicted when exceeded. Default: 50. */
  prefetchCacheSize?: number;
  root: RuntimeRoute | null;
  routes: ClientRoute[];
}

interface RouterState {
  data: Record<string, unknown>;
  /** The canonical href after server-side redirects (e.g. query-default redirect). */
  finalHref?: string;
  match: LoadedClientRoute;
  title?: string;
}

/** @internal */
export interface CacheEntry {
  createdAt: number;
  promise: Promise<RouterState | null>;
  staleTime: number;
}

/** @internal Exported for unit testing only. */
export function shouldRefetch(entry: CacheEntry): boolean {
  return Date.now() - entry.createdAt > entry.staleTime;
}

const HASH_FRAGMENT_RE = /#.*$/;

function stripHashFromHref(href: string): string {
  return href.replace(HASH_FRAGMENT_RE, "");
}

/** @internal Exported for unit testing only. */
export function buildPageElement(
  match: LoadedClientRoute,
  root: RuntimeRoute | null,
  data: Record<string, unknown>
): React.ReactNode {
  let element: React.ReactNode = createElement(match.component, data);

  // Collect non-root layouts from the route chain (bottom-up)
  const allLayouts: React.ComponentType<Record<string, unknown> & { children: React.ReactNode }>[] =
    [];
  let current: RuntimeRoute | undefined = match.pageRoute;
  while (current) {
    if (current.layout) {
      allLayouts.unshift(current.layout);
    }
    current = current.parent;
  }

  // If a root layout exists, the first entry in allLayouts IS the root — skip it here
  const layouts = root ? allLayouts.slice(1) : allLayouts;

  for (let i = layouts.length - 1; i >= 0; i--) {
    const Layout = layouts[i];
    if (Layout) {
      // biome-ignore lint/suspicious/noExplicitAny: spread loses `children` type info for createElement
      element = createElement(Layout, { ...data } as any, element);
    }
  }

  if (root?.layout) {
    // biome-ignore lint/suspicious/noExplicitAny: spread loses `children` type info for createElement
    element = createElement(root.layout, { ...data } as any, element);
  }

  return element;
}

/** Scrolls to a hash target or the top of the page after SPA navigation. */
function handleScrollRestoration(
  href: string,
  navigationToken: number,
  navVersion: { current: number }
): void {
  const destUrl = new URL(href, window.location.origin);
  if (destUrl.hash) {
    const id = decodeURIComponent(destUrl.hash.slice(1));
    const scrollToHashTarget = () => {
      if (navVersion.current !== navigationToken) {
        return;
      }

      const element = document.getElementById(id);
      if (element) {
        element.scrollIntoView({ behavior: "instant", block: "start" });
      }
    };

    window.requestAnimationFrame(() => {
      scrollToHashTarget();
      if (document.getElementById(id)) {
        return;
      }

      window.requestAnimationFrame(() => {
        scrollToHashTarget();
      });
    });
  } else {
    window.scrollTo(0, 0);
  }
}

/** Strips basePath prefix from a physical pathname, returning the logical path. */
function toLogical(physicalPathname: string, basePath: string): string {
  if (
    basePath &&
    physicalPathname.startsWith(basePath) &&
    // Require a path boundary after the prefix so "/furin" doesn't match "/furinity/foo"
    (physicalPathname.length === basePath.length || physicalPathname[basePath.length] === "/")
  ) {
    return physicalPathname.slice(basePath.length) || "/";
  }
  return physicalPathname;
}

export function RouterProvider({
  routes,
  root,
  initialMatch,
  initialData,
  autoRefresh = true,
  basePath = "",
  defaultPreload = "intent",
  defaultPreloadDelay = 50,
  defaultPreloadStaleTime = 30_000,
  prefetchCacheSize = 50,
}: RouterProviderProps): React.ReactElement {
  const [state, setState] = useState<RouterState>({
    match: initialMatch,
    data: initialData,
  });
  const [isNavigating, setIsNavigating] = useState(false);
  // currentHref stores the LOGICAL path (basePath stripped) so Link active-state
  // detection works with route patterns that never include the basePath prefix.
  const [currentHref, setCurrentHref] = useState<string>(() => {
    if (typeof window === "undefined") {
      return "/";
    }
    return toLogical(window.location.pathname, basePath) + window.location.search;
  });
  const prefetchCache = useRef(new Map<string, CacheEntry>());
  /** Monotonic counter to discard stale navigations (race condition guard). */
  const navVersion = useRef(0);

  const fetchPageState = useCallback(
    async (logicalHref: string): Promise<RouterState | null> => {
      try {
        // Physical href: what the browser/server actually receives.
        // For basePath deployments: fetch("/furin/docs/routing") not fetch("/docs/routing").
        const physicalHref = basePath + logicalHref;
        const url = new URL(physicalHref, window.location.origin);
        // Route matching always uses the LOGICAL pathname (basePath stripped).
        const logicalPathname = toLogical(url.pathname, basePath);
        const match = routes.find((r) => r.regex.test(logicalPathname));
        if (!match) {
          return null;
        }

        // Parallelize HTML data fetch + JS chunk load for this route.
        // The browser module cache makes match.load() near-instant for already-loaded pages.
        const [res, loadedMod] = await Promise.all([fetch(physicalHref), match.load()]);

        // Stale-deploy detection: if the server reports a different buildId, the client
        // bundle is outdated and SPA navigation would mount wrong components / stale code.
        // Force a full page reload to pick up the new bundle.
        const serverBuildId = res.headers.get("x-furin-build-id");
        if (serverBuildId) {
          const metaEl =
            typeof document === "undefined"
              ? null
              : document.querySelector<HTMLMetaElement>('meta[name="furin-build-id"]');
          const clientBuildId = metaEl?.content;
          if (clientBuildId && serverBuildId !== clientBuildId) {
            window.location.href = physicalHref;
            return null;
          }
        }

        // Server error — bail out so we don't render with incomplete/missing data.
        // The `navigate` fallback will do a full-page load to show the proper error page.
        if (!res.ok) {
          log.warn({ action: "navigate_server_error", href: physicalHref, status: res.status });
          return null;
        }

        // Detect server-side redirects (e.g. query-default redirect /?→/?city=Paris).
        // fetch() follows 302 automatically; res.url is the final URL, res.redirected is true.
        // Detect server-side redirects (e.g. query-default redirect /?→/?city=Paris).
        // Convert the physical redirect URL back to a logical href (basePath stripped).
        let finalHref: string | undefined;
        if (res.redirected) {
          const final = new URL(res.url);
          finalHref = toLogical(final.pathname, basePath) + final.search;
        }

        const html = await res.text();
        const doc = new DOMParser().parseFromString(html, "text/html");

        const dataEl = doc.getElementById("__FURIN_DATA__");
        const data = dataEl ? JSON.parse(dataEl.textContent || "{}") : {};

        const loadedMatch: LoadedClientRoute = {
          ...match,
          component: loadedMod.default.component,
          pageRoute: loadedMod.default._route,
        };

        return { match: loadedMatch, data, title: doc.title, finalHref };
      } catch (err: unknown) {
        log.error({ action: "navigate_failed", href: basePath + logicalHref, error: String(err) });
        return null;
      }
    },
    [routes, basePath]
  );

  const invalidatePrefetch = useCallback((path: string, type: "page" | "layout" = "page") => {
    const normalizedPath = stripHashFromHref(path);

    if (type === "page") {
      for (const key of [...prefetchCache.current.keys()]) {
        if (stripHashFromHref(key) === normalizedPath) {
          prefetchCache.current.delete(key);
        }
      }
      return;
    }

    // layout: prefix match — evict the path itself and all nested children
    const prefix =
      normalizedPath === "/" || normalizedPath.endsWith("/")
        ? normalizedPath
        : `${normalizedPath}/`;
    for (const key of [...prefetchCache.current.keys()]) {
      const normalizedKey = stripHashFromHref(key);
      if (normalizedKey === normalizedPath || normalizedKey.startsWith(prefix)) {
        prefetchCache.current.delete(key);
      }
    }
  }, []);

  const prefetch = useCallback(
    (href: string, opts?: { staleTime?: number }) => {
      const staleTime = opts?.staleTime ?? defaultPreloadStaleTime;
      const existing = prefetchCache.current.get(href);
      if (existing && !shouldRefetch(existing)) {
        return;
      }
      prefetchCache.current.set(href, {
        promise: fetchPageState(href),
        createdAt: Date.now(),
        staleTime,
      });
      // Evict the oldest entry when the cap is exceeded
      if (prefetchCache.current.size > prefetchCacheSize) {
        const oldest = prefetchCache.current.keys().next().value as string;
        prefetchCache.current.delete(oldest);
      }
    },
    [fetchPageState, defaultPreloadStaleTime, prefetchCacheSize]
  );

  const navigate = useCallback(
    async (logicalHref: string, opts?: { replace?: boolean; resetScroll?: boolean }) => {
      // logicalHref is the route-relative path (no basePath).
      // The prefetch cache is keyed by logical hrefs.
      prefetch(logicalHref);
      const myVersion = ++navVersion.current;
      setIsNavigating(true);
      try {
        const newState = await prefetchCache.current.get(logicalHref)?.promise;
        // Discard if a newer navigation was started while we were waiting
        if (navVersion.current !== myVersion) {
          return;
        }
        if (!newState) {
          log.warn({
            action: "navigate_fallback",
            href: logicalHref,
            reason: "prefetch_returned_null",
          });
          // Fall back to full-page navigation using the physical URL.
          window.location.href = basePath + logicalHref;
          return;
        }
        setState(newState);
        if (newState.title) {
          document.title = newState.title;
        }
        // effectiveHref is logical (finalHref from fetchPageState is also logical).
        const effectiveLogical = newState.finalHref ?? logicalHref;
        // Push the PHYSICAL path to browser history.
        const physicalEffective = basePath + effectiveLogical;
        if (opts?.replace) {
          window.history.replaceState(null, "", physicalEffective);
        } else {
          window.history.pushState(null, "", physicalEffective);
        }
        // Store the LOGICAL path in currentHref so Link active-state works.
        const effectiveUrl = new URL(physicalEffective, window.location.origin);
        const logicalPath = toLogical(effectiveUrl.pathname, basePath);
        setCurrentHref(logicalPath + effectiveUrl.search);
        if (opts?.resetScroll ?? true) {
          handleScrollRestoration(physicalEffective, myVersion, navVersion);
        }
      } finally {
        // Only clear navigating flag if this is still the latest navigation
        if (navVersion.current === myVersion) {
          setIsNavigating(false);
        }
      }
    },
    [prefetch, basePath]
  );

  const refresh = useCallback(
    async (opts?: { resetScroll?: boolean }) => {
      // Convert the physical browser URL to a logical href before navigating.
      const logicalPath = toLogical(window.location.pathname, basePath);
      const logicalHref = logicalPath + window.location.search;
      // Bust the cache for this exact logical page so navigate always re-fetches
      invalidatePrefetch(logicalHref, "page");
      await navigate(logicalHref, { replace: true, resetScroll: opts?.resetScroll ?? false });
    },
    [navigate, invalidatePrefetch, basePath]
  );

  const handlePopState = useCallback(async () => {
    // Convert physical browser URL to logical href for cache lookup + fetchPageState.
    const logicalPath = toLogical(window.location.pathname, basePath);
    const logicalHref = logicalPath + window.location.search;
    const myVersion = ++navVersion.current;
    setIsNavigating(true);
    try {
      // Check prefetch cache before fetching fresh (keyed by logical href)
      const cached = prefetchCache.current.get(logicalHref);
      let newState: RouterState | null;
      if (cached && !shouldRefetch(cached)) {
        newState = await cached.promise;
      } else {
        newState = await fetchPageState(logicalHref);
      }
      // Discard if a newer navigation was started while we were waiting
      if (navVersion.current !== myVersion) {
        return;
      }
      if (!newState) {
        log.warn({
          action: "popstate_fallback",
          href: logicalHref,
          reason: "fetchPageState_returned_null",
        });
        window.location.reload();
        return;
      }
      setState(newState);
      if (newState.title) {
        document.title = newState.title;
      }
      // effectiveHref is logical (includes search); push physical to history if server redirected.
      const effectiveLogical = newState.finalHref ?? logicalHref;
      if (newState.finalHref) {
        window.history.replaceState(null, "", basePath + effectiveLogical);
      }
      // effectiveLogical already contains the search params — no URL round-trip needed.
      setCurrentHref(effectiveLogical);
      // No scrollTo(0, 0) — browser handles scroll restoration
    } finally {
      if (navVersion.current === myVersion) {
        setIsNavigating(false);
      }
    }
  }, [fetchPageState, basePath]);

  // Handle browser back/forward
  useEffect(() => {
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, [handlePopState]);

  // Intercept all window.fetch calls to auto-process X-Furin-Revalidate headers.
  // This ensures that API routes calling revalidatePath() automatically bust the
  // client prefetch cache, even for non-navigation fetches (e.g. form submissions).
  // When autoRefresh=true (default), also re-fetches the current page if it was invalidated.
  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    const originalFetch = window.fetch;
    const wrapped = async (...args: Parameters<typeof fetch>): Promise<Response> => {
      const response = await originalFetch.apply(window, args);
      const invalidated: Array<{ path: string; type: "page" | "layout" }> = [];
      applyRevalidateHeader(response.headers, (path, type = "page") => {
        invalidatePrefetch(path, type);
        invalidated.push({ path, type });
      });
      if (autoRefresh && invalidated.length > 0) {
        const currentPath = window.location.pathname + window.location.search;
        if (shouldAutoRefreshPath(currentPath, invalidated)) {
          // fire-and-forget: don't block the original fetch caller
          refresh();
        }
      }
      return response;
    };
    // Copy static fetch methods (e.g. preconnect) so the patched value satisfies typeof fetch.
    Object.assign(wrapped, originalFetch);
    // biome-ignore lint/suspicious/noExplicitAny: Object.assign copies all static props but TS can't infer it
    window.fetch = wrapped as any;
    return () => {
      window.fetch = originalFetch;
    };
  }, [invalidatePrefetch, refresh, autoRefresh]);

  return createElement(
    RouterContext.Provider,
    {
      value: {
        basePath,
        currentHref,
        navigate,
        prefetch,
        refresh,
        invalidatePrefetch,
        isNavigating,
        defaultPreload,
        defaultPreloadDelay,
        defaultPreloadStaleTime,
      },
    },
    buildPageElement(state.match, root, state.data)
  ) as React.ReactElement;
}

// ── Link ───────────────────────────────────────────────────────────────────────

interface LinkView {
  extraProps: React.AnchorHTMLAttributes<HTMLAnchorElement>;
  href: string;
  isActive: boolean;
  logicalHref: string;
  resolvedChildren: React.ReactNode;
}

/**
 * Shared href/active-state/props computation used by both LinkInteractive (CSR)
 * and renderLinkElement (SSR). Centralising this keeps the two render paths in sync.
 */
function computeLinkView<To extends RouteTo>(
  {
    to,
    search,
    hash,
    children,
    activeProps,
    inactiveProps,
  }: Pick<LinkProps<To>, "to" | "search" | "hash" | "children" | "activeProps" | "inactiveProps">,
  router: RouterContextValue
): LinkView {
  const logicalHref = buildHref(
    to as string,
    search as Record<string, unknown> | null | undefined,
    hash
  );
  const logicalHrefWithoutHash = buildHref(
    to as string,
    search as Record<string, unknown> | null | undefined,
    undefined
  );
  const href = router.basePath + logicalHref;
  const isActive = router.currentHref === logicalHrefWithoutHash;
  const resolvedChildren = typeof children === "function" ? children({ isActive }) : children;
  const extraProps: React.AnchorHTMLAttributes<HTMLAnchorElement> = {
    ...(inactiveProps && !isActive ? inactiveProps() : {}),
    ...(activeProps ? activeProps({ isActive }) : {}),
  };
  return { logicalHref, href, isActive, resolvedChildren, extraProps };
}

/**
 * Full interactive Link — only rendered on the client where hooks are safe.
 * Never rendered during SSR so it's immune to duplicate-React-instance issues
 * that can arise when page modules are loaded via the furin-dev-page virtual
 * namespace (Bun HMR).
 */
function LinkInteractive<To extends RouteTo>({
  to,
  search,
  hash,
  preload,
  preloadDelay,
  preloadStaleTime,
  replace,
  disabled,
  resetScroll,
  activeProps,
  inactiveProps,
  onClick,
  onMouseEnter,
  onMouseLeave,
  onFocus,
  children,
  ...anchorProps
}: LinkProps<To>): React.ReactElement {
  const router = useRouter();
  const anchorRef = useRef<HTMLAnchorElement>(null);
  const intentTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // logicalHref: route-relative path (no basePath), used for navigation + active state.
  // physicalHref (href): what the browser sees — basePath + logicalHref.
  const { logicalHref, href, isActive, resolvedChildren, extraProps } = computeLinkView(
    { to, search, hash, children, activeProps, inactiveProps },
    router
  );

  const effectivePreload = preload ?? router.defaultPreload;
  const effectiveDelay = preloadDelay ?? router.defaultPreloadDelay;
  const effectiveStaleTime = preloadStaleTime ?? router.defaultPreloadStaleTime;

  const triggerPrefetch = useCallback(() => {
    // prefetch() expects the logical href (no basePath prefix).
    router.prefetch(logicalHref, { staleTime: effectiveStaleTime });
  }, [router, logicalHref, effectiveStaleTime]);

  // "render": preload immediately on mount
  useEffect(() => {
    if (effectivePreload === "render") {
      triggerPrefetch();
    }
  }, [effectivePreload, triggerPrefetch]);

  // "viewport": preload when link enters viewport
  useEffect(() => {
    if (effectivePreload !== "viewport" || !anchorRef.current) {
      return;
    }
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry?.isIntersecting) {
          triggerPrefetch();
          observer.disconnect();
        }
      },
      { rootMargin: "200px" }
    );
    observer.observe(anchorRef.current);
    return () => observer.disconnect();
  }, [effectivePreload, triggerPrefetch]);

  const isInternal = (url: string): boolean => {
    try {
      return new URL(url, window.location.origin).origin === window.location.origin;
    } catch {
      return false;
    }
  };

  const handleClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onClick?.(e);
    if (e.defaultPrevented || disabled) {
      return;
    }
    // Let browser handle modifier+click (new tab, etc.)
    if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) {
      return;
    }
    // Let browser handle non-self targets (e.g. target="_blank")
    if (anchorProps.target && anchorProps.target !== "_self") {
      return;
    }
    // Let browser handle external links
    if (!isInternal(href)) {
      return;
    }
    e.preventDefault();
    // navigate() expects the logical href (no basePath prefix).
    router.navigate(logicalHref, { replace, resetScroll: resetScroll ?? true });
  };

  const handleMouseEnter = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onMouseEnter?.(e);
    if (!disabled && effectivePreload === "intent" && isInternal(href)) {
      intentTimerRef.current = setTimeout(triggerPrefetch, effectiveDelay);
    }
  };

  const handleMouseLeave = (e: React.MouseEvent<HTMLAnchorElement>) => {
    onMouseLeave?.(e);
    if (intentTimerRef.current !== null) {
      clearTimeout(intentTimerRef.current);
      intentTimerRef.current = null;
    }
  };

  const handleFocus = (e: React.FocusEvent<HTMLAnchorElement>) => {
    onFocus?.(e);
    if (!disabled && effectivePreload === "intent" && isInternal(href)) {
      triggerPrefetch();
    }
  };

  return createElement(
    "a",
    {
      ref: anchorRef,
      href,
      onClick: handleClick,
      onMouseEnter: handleMouseEnter,
      onMouseLeave: handleMouseLeave,
      onFocus: handleFocus,
      ...(isActive ? { "data-status": "active" } : {}),
      ...anchorProps,
      ...extraProps,
      ...(disabled ? { "aria-disabled": true } : {}),
    },
    resolvedChildren
  );
}

// ── SSR fallback router ────────────────────────────────────────────────────────

/**
 * Static fallback used by Link during SSR when there is no RouterProvider.
 * Must not reference `window` — this object is created at module parse time.
 */
const SSR_FALLBACK_ROUTER: RouterContextValue = {
  basePath: "",
  currentHref: "/",
  navigate: () => Promise.resolve(),
  prefetch: () => {
    /* noop */
  },
  invalidatePrefetch: () => {
    /* noop */
  },
  refresh: () => Promise.resolve(),
  isNavigating: false,
  defaultPreload: "intent",
  defaultPreloadDelay: 50,
  defaultPreloadStaleTime: 30_000,
};

/**
 * Pure render helper — no hooks, safe to call from any context including SSR.
 * Computes href, active state, and applies activeProps / inactiveProps before
 * returning the final `<a>` element.
 */
function renderLinkElement<To extends RouteTo>(
  props: LinkProps<To>,
  router: RouterContextValue
): React.ReactElement {
  const { href, isActive, resolvedChildren, extraProps } = computeLinkView(props, router);

  // Destructure to strip Link-specific and client-only props before spreading onto <a>.
  const {
    to: _to,
    search: _search,
    hash: _hash,
    children: _children,
    activeProps: _ap,
    inactiveProps: _ip,
    disabled,
    preload: _p,
    preloadDelay: _pd,
    preloadStaleTime: _ps,
    replace: _r,
    resetScroll: _rs,
    onClick: _oc,
    onMouseEnter: _ome,
    onMouseLeave: _oml,
    onFocus: _of,
    ...anchorProps
  } = props;

  return createElement(
    "a",
    {
      href,
      ...(isActive ? { "data-status": "active" } : {}),
      ...anchorProps,
      ...extraProps,
      ...(disabled ? { "aria-disabled": true } : {}),
    },
    resolvedChildren
  );
}

/**
 * SSR-aware Link component.
 *
 * - **Server (SSR):** uses `RouterContext.Consumer` (a render-prop, not a hook)
 *   to read basePath / currentHref from any enclosing RouterProvider, then
 *   falls back to `SSR_FALLBACK_ROUTER` when no provider is present.
 *   `Context.Consumer` bypasses `ReactCurrentDispatcher` entirely, so it is
 *   safe even when two React instances coexist in the module graph (Bun HMR).
 * - **Client:** delegates to `LinkInteractive` which adds preloading, SPA
 *   navigation, active-state tracking and all other interactive features.
 */
export function Link<To extends RouteTo>(props: LinkProps<To>): React.ReactElement {
  if (typeof window === "undefined") {
    // Use Context.Consumer instead of useContext — the Consumer is processed
    // by react-dom/server directly (no dispatcher lookup), so it works even
    // when link.tsx is loaded under a second React instance via the
    // furin-dev-page virtual namespace after a Bun HMR reload.
    return createElement(RouterContext.Consumer, {
      // biome-ignore lint/correctness/noChildrenProp: render-prop pattern requires children-as-function
      children: (routerCtx: RouterContextValue | null) =>
        renderLinkElement(props, routerCtx ?? SSR_FALLBACK_ROUTER),
    });
  }

  // ── Client rendering ──────────────────────────────────────────────────────
  return createElement(
    LinkInteractive as React.ComponentType<LinkProps<RouteTo>>,
    props as LinkProps<RouteTo>
  );
}
