import { existsSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { runBunBuild } from "../build/bun-build.ts";
import { generateCompileEntry } from "../build/compile-entry.ts";
import { type BuildEntryOptions, buildEntrySource } from "../build/entry-template.ts";
import { productionInstrumentationPlugin } from "../build/production-instrumentation.ts";
import { buildTargetManifest, copyDirRecursive, ensureDir, toPosixPath } from "../build/shared.ts";
import type { BuildAppOptions, TargetBuildManifest } from "../build/types.ts";
import { createVirtualBuildEntry, type VirtualBuildEntry } from "../build/virtual-entry.ts";
import type { BuildTarget } from "../config.ts";
import { createRoutesPlugin } from "../plugin/routes.ts";
import { isomorphicTransformPlugin } from "../plugin/transform-isomorphic.ts";
import { environmentGuardPlugin } from "../rsc/build/environment.ts";
import { clientDirNameForPrefix } from "../shared/prefix.ts";
import { buildRuntimeAppsSequentially, type RuntimeTargetApp } from "./runtime-build.ts";

function generateDiskEntry(options: BuildEntryOptions): VirtualBuildEntry {
  ensureDir(options.outDir);
  const source = buildEntrySource({
    apps: options.apps.map(({ embed: _embed, ...context }) => context),
    headerComment: "// Auto-generated by furin build - do not edit",
    serverEntry: options.serverEntry,
  });
  const entryPath = join(options.outDir, "server.ts");
  return createVirtualBuildEntry(entryPath, source, "ts");
}

function collectEmbeddedAssets(
  entryApps: BuildEntryOptions["apps"],
  publicDir: string | undefined,
  compile: BuildAppOptions["compile"]
): string[] | undefined {
  if (compile !== "embed") {
    return;
  }
  const assets = entryApps.flatMap((app) => (app.embed ? [app.embed.clientDir] : []));
  if (publicDir !== undefined) {
    assets.push(publicDir);
  }
  return assets;
}

export async function buildBunTarget(
  apps: RuntimeTargetApp[],
  rootDir: string,
  buildRoot: string,
  serverEntry: string | null,
  options: BuildAppOptions
): Promise<TargetBuildManifest> {
  if (options.compile && !serverEntry) {
    throw new Error(
      `[furin] \`compile: "${options.compile}"\` requires a server entry point. ` +
        "Create src/server.ts or set `serverEntry` in your furin.config.ts."
    );
  }
  if (apps.length === 0) {
    throw new Error("[furin] buildBunTarget requires at least one app.");
  }

  const target = "bun" satisfies BuildTarget;
  const targetManifest = buildTargetManifest(rootDir, buildRoot, target, serverEntry);
  const targetDir = resolve(rootDir, targetManifest.targetDir);

  rmSync(targetDir, { force: true, recursive: true });
  ensureDir(targetDir);

  const publicDir = existsSync(join(rootDir, "public")) ? join(rootDir, "public") : undefined;
  const { entryApps, headlineBuildId } = await buildRuntimeAppsSequentially(
    apps,
    targetDir,
    serverEntry,
    options,
    "bun"
  );
  targetManifest.buildId = headlineBuildId;
  if (serverEntry) {
    targetManifest.rscManifestPath = toPosixPath(
      join(targetManifest.targetDir, "rsc", "manifest.json")
    );
  }

  const targetPublicDir = publicDir ? join(targetDir, "public") : undefined;
  if (publicDir && targetPublicDir && options.compile !== "embed") {
    copyDirRecursive(publicDir, targetPublicDir);
  }

  if (options.compile && serverEntry) {
    const outfile = join(targetDir, "server");

    const entry = generateCompileEntry({
      apps: entryApps,
      outDir: targetDir,
      publicDir,
      serverEntry,
    });
    const embeddedAssets = collectEmbeddedAssets(entryApps, publicDir, options.compile);

    await runBunBuild({
      bytecode: true,
      compile: { assets: embeddedAssets, outfile },
      define: { "process.env.NODE_ENV": JSON.stringify("production") },
      entrypoints: [entry.entrypoint],
      files: entry.files,
      format: "esm",
      minify: true,
      plugins: [
        entry.plugin,
        productionInstrumentationPlugin(),
        ...(options.plugins ?? []),
        createRoutesPlugin({ instances: apps, target: "server" }),
        isomorphicTransformPlugin("server"),
        environmentGuardPlugin("ssr"),
      ],
      sourcemap: "none",
      splitting: true,
      target: "bun",
    });

    console.log(`[furin] Server binary: ${outfile}`);

    targetManifest.serverPath = toPosixPath(join(targetManifest.targetDir, "server"));

    // Embed mode: assets are in the binary — clean up client dirs too.
    if (options.compile === "embed") {
      for (const app of apps) {
        rmSync(join(targetDir, clientDirNameForPrefix(app.prefix)), {
          force: true,
          recursive: true,
        });
      }
      targetManifest.clientDir = null;
      targetManifest.templatePath = null;
    }
  } else if (serverEntry) {
    // Disk mode: generate server.ts then bundle it into self-contained server.js
    const entry = generateDiskEntry({
      apps: entryApps,
      outDir: targetDir,
      serverEntry,
    });

    await runBunBuild({
      entrypoints: [entry.entrypoint],
      files: entry.files,
      minify: true,
      naming: { chunk: "[name]-[hash].[ext]", entry: "[name].[ext]" },
      outdir: targetDir,
      plugins: [
        entry.plugin,
        productionInstrumentationPlugin(),
        ...(options.plugins ?? []),
        createRoutesPlugin({ instances: apps, target: "server" }),
        isomorphicTransformPlugin("server"),
        environmentGuardPlugin("ssr"),
      ],
      sourcemap: "none",
      target: "bun",
    });
    console.log(
      `[furin] Server bundle: ${toPosixPath(join(targetManifest.targetDir, "server.js"))}`
    );

    targetManifest.serverPath = toPosixPath(join(targetManifest.targetDir, "server.js"));
  }

  return targetManifest;
}
