/**
 * Pre-generates src/generated/docs-content.ts for use in compiled binaries.
 * In --compile embed mode, readFileSync with import.meta.url doesn't find MDX files
 * because the MDX plugin converts them to React modules (not raw file paths).
 * This script embeds the raw text content directly into the bundle.
 *
 * Run: bun run scripts/generate-docs-content.ts
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const DOCS_DIR = resolve(import.meta.dir, "..");

const SOURCE_PATHS = [
  "src/content/docs/introduction.mdx",
  "src/content/docs/getting-started.mdx",
  "src/content/docs/routing.mdx",
  "src/content/docs/data-loading.mdx",
  "src/content/docs/rendering.mdx",
  "src/content/docs/layouts.mdx",
  "src/content/docs/api-routes.mdx",
  "src/content/docs/plugins.mdx",
  "src/content/docs/deployment.mdx",
  "src/content/docs/dev-hmr.mdx",
];

const entries = SOURCE_PATHS.map((sourcePath) => {
  const fullPath = resolve(DOCS_DIR, sourcePath);
  const content = readFileSync(fullPath, "utf8");
  return `  ${JSON.stringify(sourcePath)}: ${JSON.stringify(content)},`;
});

const output = [
  "// Auto-generated by scripts/generate-docs-content.ts — do not edit manually.",
  "// Run: bun run generate:content",
  "export const DOCS_CONTENT: Record<string, string> = {",
  ...entries,
  "};",
  "",
].join("\n");

const outPath = resolve(DOCS_DIR, "src/generated/docs-content.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, output, "utf8");
console.log(`✓ src/generated/docs-content.ts  (${SOURCE_PATHS.length} docs)`);
