import "../../../packages/core/tests/setup/global.ts";
import { expect, mock, test } from "bun:test";
import { treaty } from "@elysia/eden";
import { withSync } from "@teyik0/furin/client";
import { Elysia } from "elysia";
import {
  installDom,
  resetDomState,
  useDomTests as setupDomTests,
} from "../../../packages/core/tests/support/dom.ts";

installDom();
resetDomState();

const { act, createElement } = await import("react");
const { createRoot } = await import("react-dom/client");

setupDomTests();

const createCalls: unknown[][] = [];

const app = new Elysia().post("/boards", ({ body, headers }) => {
  createCalls.push([body, { headers: { "Idempotency-Key": headers["idempotency-key"] } }]);
  return { id: "board-created" };
});
mock.module("../src/lib/api", () => ({
  api: withSync(
    treaty<typeof app>(window.location.origin, {
      fetcher: ((input, init) => app.handle(new Request(input, init))) as typeof fetch,
    })
  ),
}));

const { CreateBoardForm } = await import("../src/components/create-board-form");

function setInputValue(element: HTMLInputElement, value: string): void {
  const setter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(element), "value")?.set;
  setter?.call(element, value);
  const EventConstructor = document.defaultView?.Event ?? Event;
  element.dispatchEvent(new EventConstructor("input", { bubbles: true }));
  element.dispatchEvent(new EventConstructor("change", { bubbles: true }));
}

test("creates a board with the idempotency key generated by the enriched Eden client", async () => {
  const container = document.createElement("div");
  const root = createRoot(container);
  document.body.appendChild(container);

  try {
    await act(() => root.render(createElement(CreateBoardForm)));
    const input = container.querySelector<HTMLInputElement>('input[aria-label="New board name"]');
    const form = input?.closest("form");
    expect(input).not.toBeNull();
    expect(form).not.toBeNull();

    await act(() => {
      if (input) {
        setInputValue(input, "Project Beta");
      }
    });
    await act(async () => {
      form?.querySelector<HTMLButtonElement>('button[type="submit"]')?.click();
      await Promise.resolve();
    });

    expect(createCalls).toHaveLength(1);
    expect(createCalls[0]?.[0]).toEqual({ name: "Project Beta" });
    expect(createCalls[0]?.[1]).toEqual({
      headers: { "Idempotency-Key": expect.any(String) },
    });
    expect(input?.value).toBe("");
  } finally {
    await act(() => root.unmount());
    container.remove();
  }
});
