import "../../../packages/core/tests/setup/global.ts";
import { afterEach, expect, mock, test } from "bun:test";
import { treaty } from "@elysia/eden";
import { withSync } from "@teyik0/furin/client";
import { Elysia } from "elysia";
import {
  installDom,
  resetDomState,
  useDomTests as setupDomTests,
} from "../../../packages/core/tests/support/dom.ts";

installDom();
resetDomState();

const { act, createElement } = await import("react");
const { createRoot } = await import("react-dom/client");

setupDomTests();

const createCalls: unknown[][] = [];
let createResponse: Promise<Response> | undefined;
let transportFailure: Error | undefined;

const app = new Elysia().post("/boards", ({ body, headers }) => {
  createCalls.push([body, { headers: { "Idempotency-Key": headers["idempotency-key"] } }]);
  return createResponse ?? { id: "board-created" };
});
mock.module("../src/lib/api", () => ({
  api: withSync(
    treaty<typeof app>(window.location.origin, {
      fetcher: ((input, init) => {
        if (transportFailure) {
          return Promise.reject(transportFailure);
        }
        return app.handle(new Request(input, init));
      }) as typeof fetch,
    })
  ),
}));

const { CreateBoardForm } = await import("../src/components/create-board-form");

afterEach(() => {
  createCalls.length = 0;
  createResponse = undefined;
  transportFailure = undefined;
});

test.each(["network", "empty", "text", "json-null", "invalid-json"])(
  "keeps board creation retryable after a %s failure",
  async (failure) => {
    if (failure === "network") {
      transportFailure = new TypeError("Failed to fetch");
    } else if (failure === "json-null") {
      createResponse = Promise.resolve(Response.json(null, { status: 502 }));
    } else if (failure === "invalid-json") {
      createResponse = Promise.resolve(
        new Response("invalid", { headers: { "Content-Type": "application/json" }, status: 502 })
      );
    } else {
      createResponse = Promise.resolve(
        new Response(failure === "empty" ? null : "Bad gateway", { status: 502 })
      );
    }
    const container = document.createElement("div");
    document.body.appendChild(container);
    const root = createRoot(container);
    try {
      await act(() => root.render(createElement(CreateBoardForm)));
      const input = container.querySelector<HTMLInputElement>("input");
      const button = container.querySelector<HTMLButtonElement>('button[type="submit"]');
      await act(() => {
        if (input) {
          setInputValue(input, "My draft");
        }
      });
      await act(async () => {
        button?.click();
        await Promise.resolve();
      });
      expect(container.textContent).toContain("Could not create the board. Please try again.");
      expect(input?.value).toBe("My draft");
      expect(button?.disabled).toBe(false);
      transportFailure = undefined;
      createResponse = undefined;
      await act(async () => {
        button?.click();
        await Promise.resolve();
      });
      expect(input?.value).toBe("");
      expect(container.textContent).not.toContain("Could not create the board.");
    } finally {
      await act(() => root.unmount());
      container.remove();
    }
  }
);

function setInputValue(element: HTMLInputElement, value: string): void {
  const setter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(element), "value")?.set;
  setter?.call(element, value);
  const EventConstructor = document.defaultView?.Event ?? Event;
  element.dispatchEvent(new EventConstructor("input", { bubbles: true }));
  element.dispatchEvent(new EventConstructor("change", { bubbles: true }));
}

test("creates a board with the idempotency key generated by the enriched Eden client", async () => {
  const container = document.createElement("div");
  const root = createRoot(container);
  document.body.appendChild(container);

  try {
    await act(() => root.render(createElement(CreateBoardForm)));
    const input = container.querySelector<HTMLInputElement>('input[aria-label="New board name"]');
    const form = input?.closest("form");
    expect(input).not.toBeNull();
    expect(form).not.toBeNull();

    await act(() => {
      if (input) {
        setInputValue(input, "Project Beta");
      }
    });
    await act(async () => {
      form?.querySelector<HTMLButtonElement>('button[type="submit"]')?.click();
      await Promise.resolve();
    });

    expect(createCalls).toHaveLength(1);
    expect(createCalls[0]?.[0]).toEqual({ name: "Project Beta" });
    expect(createCalls[0]?.[1]).toEqual({
      headers: { "Idempotency-Key": expect.any(String) },
    });
    expect(input?.value).toBe("");
  } finally {
    await act(() => root.unmount());
    container.remove();
  }
});

test("preserves the board name after rejection and clears it after a successful retry", async () => {
  const response = Promise.withResolvers<Response>();
  const retry = Promise.withResolvers<Response>();
  createResponse = response.promise;
  const container = document.createElement("div");
  const root = createRoot(container);
  document.body.appendChild(container);

  try {
    await act(() => root.render(createElement(CreateBoardForm)));
    const input = container.querySelector<HTMLInputElement>('input[aria-label="New board name"]');
    const button = container.querySelector<HTMLButtonElement>('button[type="submit"]');
    await act(() => {
      if (input) {
        setInputValue(input, " Project Beta ");
      }
    });
    await act(async () => {
      button?.click();
      await Promise.resolve();
    });
    expect(input?.disabled).toBe(true);
    expect(button?.disabled).toBe(true);
    expect(button?.textContent).toContain("Creating…");
    expect(createCalls[0]?.[0]).toEqual({ name: "Project Beta" });

    await act(async () => {
      response.resolve(Response.json({ detail: "Creation rejected" }, { status: 422 }));
      await response.promise;
    });
    expect(input?.value).toBe(" Project Beta ");
    expect(input?.disabled).toBe(false);
    expect(button?.disabled).toBe(false);
    expect(container.textContent).toContain("Creation rejected");

    createResponse = retry.promise;
    await act(async () => {
      button?.click();
      await Promise.resolve();
    });
    expect(container.textContent).not.toContain("Creation rejected");
    await act(async () => {
      retry.resolve(Response.json({ id: "board-created" }));
      await retry.promise;
    });
    expect(createCalls).toHaveLength(2);
    expect(input?.value).toBe("");
    expect(button?.disabled).toBe(false);
  } finally {
    response.resolve(Response.json({ id: "board-created" }));
    retry.resolve(Response.json({ id: "board-created" }));
    await act(() => root.unmount());
    container.remove();
  }
});
