name: Workflow - CD

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    name: Workflow - CD
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: Cache bun
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}

      - name: 'Setup Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Lint & Format Check
        run: bun run ultracite check

      - name: Build
        run: bun run build

      - name: Type Check
        run: bun run test:types

      - name: Test
        run: bun run test

      - name: Setup auth for Bun
        working-directory: packages/core
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc

      - name: Publish
        working-directory: packages/core
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
